import fs from 'node:fs/promises';import path from 'node:path';import {hashKey} from '../memory/store';
import {discoverModule} from '../moduleDiscovery';import {inspectScript} from '../scriptTranslation';import {JsonEngine} from '../../src/services/json/jsonEngine';import {parseJsonStrict} from '../../src/services/json/strictJson';import {surroundingContext} from '../memory/context';import {moduleIdentity} from '../memory/moduleIdentity';import type {MemoryContext} from '../memory/store';
import {jsonQualityGate} from '../../src/services/validation/qualityGate';import {ProtectedContentEngine as P} from '../../src/services/protected-content/protectedContentEngine';
export interface InventoryUnit {file:string;source:string;context:MemoryContext;identity_evidence?:{document_id?:string;explicit_references:{path:string;uuid:string}[];system_identifiers:{path:string;value:string}[]}}
export function documentEvidence(original:any):NonNullable<InventoryUnit['identity_evidence']>{const refs=[['_stats.compendiumSource',original._stats?.compendiumSource],['_stats.duplicateSource',original._stats?.duplicateSource],['_stats.exportSource.uuid',original._stats?.exportSource?.uuid],['flags.core.sourceId',original.flags?.core?.sourceId],['flags.dnd5e.sourceId',original.flags?.dnd5e?.sourceId],['flags.scene-packer.sourceId',original.flags?.['scene-packer']?.sourceId]];return {document_id:typeof original._id==='string'?original._id:undefined,explicit_references:refs.filter(([,v])=>typeof v==='string'&&v.length<=512).map(([path,uuid])=>({path,uuid})),system_identifiers:typeof original.system?.identifier==='string'&&original.system.identifier.length<=512?[{path:'system.identifier',value:original.system.identifier}]:[]};}
export function canonicalContext(manifest:any,file:string,original:any,json_path:(string|number)[]):MemoryContext {
 const normalized=file.replaceAll('\\','/');const packs=Array.isArray(manifest?.packs)?manifest.packs:[];const pack=packs.find((p:any)=>typeof p.path==='string'&&normalized.startsWith(p.path.replace(/\/$/,'')+'/')&&typeof p.name==='string'&&typeof p.type==='string');
 const scoped=pack&&/^[-a-zA-Z0-9_]+$/.test(pack.name)?{pack:pack.name,system:typeof original._stats?.systemId==='string'?original._stats.systemId:typeof pack.system==='string'?pack.system:undefined}:{};
 if(!pack||typeof manifest.id!=='string'||!/^[-a-zA-Z0-9_]+$/.test(manifest.id)||!/^[-a-zA-Z0-9_]+$/.test(pack.name)||!['Actor','Item','JournalEntry','RollTable','Scene','Macro','Cards','Playlist','Adventure'].includes(pack.type)||typeof manifest.version!=='string'||!manifest.version||typeof original._id!=='string'||!/^\w{16}$/.test(original._id)||json_path[0]==='items'||json_path[0]==='pages'||json_path[0]==='effects')return scoped;
 const system=typeof original._stats?.systemId==='string'?original._stats.systemId:typeof pack.system==='string'?pack.system:undefined;
 if(!system)return scoped;return {...scoped,canonical_uuid:'Compendium.'+manifest.id+'.'+pack.name+'.'+pack.type+'.'+original._id,canonical_version:manifest.version,system};
}
export async function inventory(root:string,signal?:AbortSignal){
 root=await fs.realpath(root);const discovery=await discoverModule(root,signal),identity=await moduleIdentity(root);let manifest:any={};const manifestFile=discovery.files.find(f=>f.relative==='module.json');if(manifestFile&&(await fs.stat(manifestFile.absolute)).size<5000000)try{manifest=parseJsonStrict(await fs.readFile(manifestFile.absolute,'utf8'));}catch{}
 const units:InventoryUnit[]=[],skipped:string[]=[];const files=discovery.files.filter(f=>f.kind);const fingerprints:{file:string;size:number;mtime:number;content_hash?:string}[]=[];
 if(manifestFile){const stat=await fs.stat(manifestFile.absolute);fingerprints.push({file:'module.json',size:stat.size,mtime:stat.mtimeMs,content_hash:hashKey(manifest)});}
 for(const file of files){signal?.throwIfAborted();const stat=await fs.stat(file.absolute);fingerprints.push({file:file.relative,size:stat.size,mtime:stat.mtimeMs});if(stat.size>50000000){skipped.push(file.relative);continue;}
  if((await fs.lstat(file.absolute)).isSymbolicLink()||await fs.realpath(file.absolute)!==file.absolute)throw new Error('SOURCE_CHANGED');
  try{const source=await fs.readFile(file.absolute,'utf8');fingerprints.at(-1)!.content_hash=hashKey(source);if(file.kind==='script'){const spans=inspectScript(source);spans.forEach(span=>P.protect(span.text));spans.forEach((span,index)=>units.push({file:file.relative,source:span.text,context:{module:identity.module,document_type:'Script',field_type:'visible_literal',json_path:['script',index]}}));continue;}
   const original=parseJsonStrict(source),fields=JsonEngine.analyze(original,file.relative).fields.filter(f=>f.classification==='TRANSLATABLE');if(jsonQualityGate(source,source,fields.map(f=>f.pathSegments||[])).status==='FAILED')throw new Error('SOURCE_GATE_FAILED');
   for(const field of fields){const segments=field.pathSegments||[];units.push({file:file.relative,source:field.originalValue,identity_evidence:documentEvidence(original),context:{module:identity.module,system:typeof original._stats?.systemId==='string'?original._stats.systemId:undefined,document_type:typeof original.type==='string'?original.type:'JSON',...surroundingContext(original,segments,field.originalValue),field_type:field.path.split('.').slice(-2).join('.'),json_path:segments,...canonicalContext(manifest,file.relative,original,segments)}});}
  }catch{skipped.push(file.relative);}
 }
 // Native dictionaries are inventoried as literal keys, never executed.
 if(Array.isArray(manifest.languages)&&!manifest.languages.some((e:any)=>/^es(?:-|$)/i.test(e?.lang)))for(let i=0;i<manifest.languages.length;i++){
  const e=manifest.languages[i];if(!['en','ru'].includes(e?.lang)||typeof e.path!=='string')continue;const file=discovery.files.find(f=>f.relative.replaceAll('\\','/')===e.path);if(!file)continue;
  try{const stat=await fs.stat(file.absolute);if(stat.size>50000000)continue;const source=await fs.readFile(file.absolute,'utf8'),value=parseJsonStrict(source);fingerprints.push({file:e.path+'#languages['+i+']',size:stat.size,mtime:stat.mtimeMs,content_hash:hashKey(source)});const pending:InventoryUnit[]=[];const walk=(v:any,segments:(string|number)[])=>{if(typeof v==='string'){P.protect(v);if(/\p{L}/u.test(v))pending.push({file:e.path+'#languages['+i+']',source:v,context:{module:identity.module,document_type:'native-localization',field_type:'localization',json_path:segments}});}else if(v&&typeof v==='object'&&!Array.isArray(v))for(const key of Object.keys(v))walk(v[key],[...segments,key]);else throw new Error('LOCALIZATION_VALUE_INVALID');};walk(value,[]);units.push(...pending);}catch{skipped.push(e.path);}
 }
 return {units,files:files.length,skipped,fingerprints};
}
