import {hashKey,MemoryStore,type MemoryContext} from '../memory/store';import type {ProviderSettings} from '../contracts';import {ProtectedContentEngine as P} from '../../src/services/protected-content/protectedContentEngine';import {promptVersion} from './prompt';import {validateHtmlIntegrity} from '../../src/services/validation/htmlIntegrity';import {validateQuality} from './quality';
import {semanticChunks} from './prompt';
/** Explicit terms override persisted terms; unresolved effective conflicts are never guessed. */
export function effectiveTerms(store:MemoryStore,context:MemoryContext,explicit:{source:string;target:string}[]=[]){
 const terms=[...store.glossary(context).filter(term=>!explicit.some(user=>user.source.toLowerCase()===term.source.toLowerCase())).map(term=>({source:term.source,target:term.target})),...explicit];
 const targets=new Map<string,string>();for(const term of terms){const key=term.source.toLowerCase();if(targets.has(key)&&targets.get(key)!==term.target)throw new Error('GLOSSARY_CONFLICT');targets.set(key,term.target);}
 return terms;
}
export function cacheIdentity(store:MemoryStore,settings:ProviderSettings,source:string,language:string,context:MemoryContext,explicit:{source:string;target:string}[]=[]):import('../memory/store').CacheIdentity{return {schema_version:1,key:reuseKey(store,settings,source,language,context,explicit),source_hash:hashKey(source),source_language:language,target_language:'es',context_hash:hashKey([context.system,context.module,context.document_type,context.field_type,context.surrounding_context_hash,context.canonical_uuid,context.canonical_version,context.canonical_uuid?context.json_path:undefined]),provider:settings.provider||'ollama',model:settings.model,prompt_version:promptVersion,glossary_hash:hashKey([store.glossary(context),explicit]),rules_version:P.rulesVersion,review_revision:store.revision,pdf_fingerprint:context.system==='dnd5e'&&(store.pdfCorpus.fingerprint!=='ABSENT'||store.pdfEpoch>0)?store.pdfCorpus.fingerprint:null};}
export function estimatedSourceCalls(settings:ProviderSettings,source:string,terms:{source:string;target:string}[]=[]){
 let text=P.protect(source).protectedText;
 for(const term of [...terms].sort((a,b)=>b.source.length-a.source.length)){const escaped=term.source.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');text=text.split(/(\[\[PROTECTED_\d+\]\])/g).map(part=>/^\[\[PROTECTED_\d+\]\]$/.test(part)?part:part.replace(new RegExp('(?<![\\p{L}\\p{N}_])'+escaped+'(?![\\p{L}\\p{N}_])','giu'),'[[PROTECTED_999999]]')).join('');}
 const spans=[...new Set(text.split(/\[\[PROTECTED_\d+\]\]/g).map(s=>s.trim()).filter(Boolean))];if(!spans.length)return 0;
 try{return settings.model.startsWith('translategemma:')?semanticChunks(text).length:spans.reduce((sum,span)=>sum+semanticChunks(span).length,0);}catch{return 1;}
}
export function reuseKey(store:MemoryStore,settings:ProviderSettings,source:string,language:string,context:MemoryContext,explicit:{source:string;target:string}[]=[]){const identity=[language,'es',source,context.system,context.module,context.document_type,context.field_type,context.surrounding_context_hash,context.canonical_uuid,context.canonical_version,context.canonical_uuid?context.json_path:undefined,hashKey([store.glossary(context),explicit]),settings.provider||'ollama',settings.model,promptVersion,P.rulesVersion,'foundry-v14.368',store.revision];const scoped=context.pack&&!context.canonical_uuid?[...identity,'pack-scope-1',context.pack]:identity;return hashKey(context.system==='dnd5e'&&(store.pdfCorpus.fingerprint!=='ABSENT'||store.pdfEpoch>0)?[...scoped,'pdf-srd-reuse-1',store.pdfCorpus.fingerprint]:scoped);}
export function reusable(source:string,target:string,context:MemoryContext){const signature=(value:string)=>JSON.stringify([...P.protect(value).tokens.values()].map(t=>[t.type,t.original]));return signature(source)===signature(target)&&validateQuality(source,target).status==='PASS'&&(context.document_type==='Script'||!validateHtmlIntegrity(source,target).length);}
