import { TerminologyEntry, DisambiguationRule } from '../../types';

export const OFFICIAL_SRD_TERMS: TerminologyEntry[] = [
  // Mecánicas Core
  {
    id: 'srd-adv',
    source: 'advantage',
    target: 'ventaja',
    category: 'mechanical_term',
    context: 'Tiradas con d20: tirar 2 dados y usar el mayor',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-disadv',
    source: 'disadvantage',
    target: 'desventaja',
    category: 'mechanical_term',
    context: 'Tiradas con d20: tirar 2 dados y usar el menor',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-attack-roll',
    source: 'attack roll',
    target: 'tirada de ataque',
    category: 'mechanical_term',
    context: 'Tirada para impactar a un objetivo',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-saving-throw',
    source: 'saving throw',
    target: 'tirada de salvación',
    category: 'mechanical_term',
    context: 'Intento de resistir un efecto adverso',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-ability-check',
    source: 'ability check',
    target: 'prueba de característica',
    category: 'mechanical_term',
    context: 'Prueba usando una de las 6 características',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-critical-hit',
    source: 'critical hit',
    target: 'golpe crítico',
    category: 'mechanical_term',
    context: 'Impacto al sacar un 20 natural',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-opportunity-attack',
    source: 'opportunity attack',
    target: 'ataque de oportunidad',
    category: 'mechanical_term',
    context: 'Reacción cuando un enemigo sale de tu alcance',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-prof-bonus',
    source: 'proficiency bonus',
    target: 'bonificador por competencia',
    category: 'mechanical_term',
    context: 'Bonificador añadido según el nivel del personaje',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-spell-slot',
    source: 'spell slot',
    target: 'espacio de conjuro',
    category: 'mechanical_term',
    context: 'Recurso gastado para lanzar conjuros',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-hit-points',
    source: 'hit points',
    target: 'puntos de golpe',
    category: 'mechanical_term',
    context: 'Vitalidad del personaje o criatura',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-hit-dice',
    source: 'hit dice',
    target: 'dados de golpe',
    category: 'mechanical_term',
    context: 'Dados usados para curarse durante descansos cortos',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-armor-class',
    source: 'armor class',
    target: 'clase de armadura',
    category: 'mechanical_term',
    context: 'Número objetivo para impactar a una criatura',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-short-rest',
    source: 'short rest',
    target: 'descanso corto',
    category: 'mechanical_term',
    context: 'Periodo de descanso de al menos 1 hora',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-long-rest',
    source: 'long rest',
    target: 'descanso largo',
    category: 'mechanical_term',
    context: 'Periodo de descanso prolongado de al menos 8 horas',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-death-save',
    source: 'death saving throw',
    target: 'tirada de salvación contra la muerte',
    category: 'mechanical_term',
    context: 'Tirada especial a 0 puntos de golpe',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-magic-weapon',
    source: 'magic weapon',
    target: 'arma mágica',
    category: 'item',
    context: 'Objeto de armamento mágico o conjuro',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-passive-perception',
    source: 'passive perception',
    target: 'percepción pasiva',
    category: 'mechanical_term',
    context: 'Valor fijo 10 + bonificador de percepción',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },

  // Desambiguaciones clave
  {
    id: 'srd-feat',
    source: 'feat',
    target: 'dote',
    category: 'character_progression',
    context: 'Talento o especialización adquirible',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-feature',
    source: 'feature',
    target: 'característica',
    category: 'class_feature',
    context: 'Capacidad de clase, subclase o trasfondo',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-trait',
    source: 'trait',
    target: 'rasgo',
    category: 'species_trait',
    context: 'Propiedad o capacidad innata de una especie o linaje',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-proficiency',
    source: 'proficiency',
    target: 'competencia',
    category: 'mechanical_term',
    context: 'Adiestramiento con armas, armaduras, herramientas o salvaciones',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },
  {
    id: 'srd-skill',
    source: 'skill',
    target: 'habilidad',
    category: 'mechanical_term',
    context: 'Faceta específica de una característica (ej. Sigilo, Atletismo)',
    confidence: 'high',
    sourceDocument: 'SRD 5.2.1 / D&D 2024',
    status: 'confirmed',
  },

  // Características
  { id: 'srd-str', source: 'Strength', target: 'Fuerza', category: 'ability', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-dex', source: 'Dexterity', target: 'Destreza', category: 'ability', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-con', source: 'Constitution', target: 'Constitución', category: 'ability', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-int', source: 'Intelligence', target: 'Inteligencia', category: 'ability', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-wis', source: 'Wisdom', target: 'Sabiduría', category: 'ability', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-cha', source: 'Charisma', target: 'Carisma', category: 'ability', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },

  // Habilidades
  { id: 'srd-ath', source: 'Athletics', target: 'Atletismo', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-acro', source: 'Acrobatics', target: 'Acrobacias', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-soh', source: 'Sleight of Hand', target: 'Juego de manos', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-stealth', source: 'Stealth', target: 'Sigilo', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-arcana', source: 'Arcana', target: 'Conocimiento arcano', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-hist', source: 'History', target: 'Historia', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-inv', source: 'Investigation', target: 'Investigación', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-nat', source: 'Nature', target: 'Naturaleza', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-rel', source: 'Religion', target: 'Religión', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-ah', source: 'Animal Handling', target: 'Trato con animales', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-ins', source: 'Insight', target: 'Perspicacia', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-med', source: 'Medicine', target: 'Medicina', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-perc', source: 'Perception', target: 'Percepción', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-surv', source: 'Survival', target: 'Supervivencia', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-dec', source: 'Deception', target: 'Engaño', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-intim', source: 'Intimidation', target: 'Intimidación', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-perf', source: 'Performance', target: 'Interpretación', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-pers', source: 'Persuasion', target: 'Persuasión', category: 'skill', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },

  // Estados / Condiciones
  { id: 'srd-blind', source: 'Blinded', target: 'Cegado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-charm', source: 'Charmed', target: 'Hechizado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-deaf', source: 'Deafened', target: 'Ensordecido', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-exh', source: 'Exhaustion', target: 'Agotamiento', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-fright', source: 'Frightened', target: 'Asustado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-grap', source: 'Grappled', target: 'Agarrado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-incap', source: 'Incapacitated', target: 'Incapacitado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-invis', source: 'Invisible', target: 'Invisible', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-para', source: 'Paralyzed', target: 'Paralizado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-petr', source: 'Petrified', target: 'Petrificado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-pois', source: 'Poisoned', target: 'Envenenado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-prone', source: 'Prone', target: 'Tumbado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-restr', source: 'Restrained', target: 'Apresado', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-stun', source: 'Stunned', target: 'Aturdido', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-uncon', source: 'Unconscious', target: 'Inconsciente', category: 'condition', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },

  // Tipos de Daño
  { id: 'srd-acid', source: 'acid damage', target: 'daño por ácido', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-bludg', source: 'bludgeoning damage', target: 'daño contundente', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-cold', source: 'cold damage', target: 'daño por frío', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-fire', source: 'fire damage', target: 'daño por fuego', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-force', source: 'force damage', target: 'daño por fuerza', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-lightn', source: 'lightning damage', target: 'daño por relámpago', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-necro', source: 'necrotic damage', target: 'daño necrótico', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-pierc', source: 'piercing damage', target: 'daño perforante', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-poisond', source: 'poison damage', target: 'daño por veneno', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-psych', source: 'psychic damage', target: 'daño psíquico', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-rad', source: 'radiant damage', target: 'daño radiante', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-slash', source: 'slashing damage', target: 'daño cortante', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-thun', source: 'thunder damage', target: 'daño por trueno', category: 'damage_type', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },

  // Conjuros Frecuentes
  { id: 'srd-warding-bond', source: 'warding bond', target: 'vínculo protector', category: 'spell', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-cure-wounds', source: 'cure wounds', target: 'curar heridas', category: 'spell', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-healing-word', source: 'healing word', target: 'palabra de curación', category: 'spell', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-fireball', source: 'fireball', target: 'bola de fuego', category: 'spell', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-eldritch-blast', source: 'eldritch blast', target: 'descarga sobrenatural', category: 'spell', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-shield', source: 'shield', target: 'escudo', category: 'spell', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-mage-armor', source: 'mage armor', target: 'armadura de mago', category: 'spell', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-hunters-mark', source: "hunter's mark", target: 'marca del cazador', category: 'spell', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
  { id: 'srd-magic-missile', source: 'magic missile', target: 'proyectil mágico', category: 'spell', confidence: 'high', sourceDocument: 'SRD 5.2.1', status: 'confirmed' },
];

export const DISAMBIGUATION_RULES: DisambiguationRule[] = [
  {
    id: 'rule-feature',
    term: 'feature',
    options: [
      {
        target: 'característica',
        context: 'Clase / subclase / progresión de nivel',
        description: 'Capacidad obtenida por clase o subclase (ej. "Sneak Attack feature")',
        recommendedWhen: 'class_feature',
      },
      {
        target: 'rasgo',
        context: 'Especie / Linaje / Trasfondo',
        description: 'Capacidad innata biológica o de origen',
        recommendedWhen: 'species_trait',
      },
      {
        target: 'dote',
        context: 'Elección de progresión opcional',
        description: 'En caso de que en la fuente refiera a un talento (Feat)',
        recommendedWhen: 'feat',
      },
    ],
  },
  {
    id: 'rule-feat',
    term: 'feat',
    options: [
      {
        target: 'dote',
        context: 'Dote de personaje (D&D 2024 / SRD)',
        description: 'Talentos adquiridos a nivel 1 (Origin Feats) o 4+ (General Feats)',
        recommendedWhen: 'feat',
      },
      {
        target: 'hazaña',
        context: 'Narrativo / Texto literario',
        description: 'Acción heroica en trasfondo narrativo',
        recommendedWhen: 'lore',
      },
    ],
  },
  {
    id: 'rule-trait',
    term: 'trait',
    options: [
      {
        target: 'rasgo',
        context: 'Especie / Trasfondo / Monstruo',
        description: 'Capacidad innata o pasiva de una criatura o especie',
        recommendedWhen: 'species_trait',
      },
      {
        target: 'característica',
        context: 'Propiedad general de un objeto o entorno',
        description: 'Atributo descriptivo',
      },
    ],
  },
  {
    id: 'rule-proficiency',
    term: 'proficiency',
    options: [
      {
        target: 'competencia',
        context: 'Mecánica de reglas (armas, armaduras, salvaciones, habilidades)',
        description: 'Dominio técnico con derecho a sumar el bonificador por competencia',
      },
    ],
  },
  {
    id: 'rule-skill',
    term: 'skill',
    options: [
      {
        target: 'habilidad',
        context: 'Lista oficial de 18 habilidades de D&D',
        description: 'Subclasificación de característica (ej. Sigilo, Atletismo)',
      },
      {
        target: 'destreza',
        context: 'Lenguaje coloquial genérico',
        description: 'No recomendado en contexto reglamentario',
      },
    ],
  },
];
