import {createHash} from 'node:crypto';
import type {MemoryContext,MemoryEntry} from './store';
export type MatchType='FOUNDRY_ID'|'UUID'|'CANONICAL_ID'|'EXACT_SOURCE'|'NORMALIZED_SOURCE'|'APPROVED_MANUAL'|'PDF_REFERENCE'|'FUZZY';
export interface FieldIdentity {system:string;package:string;pack:string;document_type:string;document_id:string;field_path:(string|number)[];target_language:'es';version:string}
export interface CanonicalEvidence {schema_version:1;match_type:MatchType;decision:'VERIFIED'|'HIGH_CONFIDENCE'|'AMBIGUOUS'|'REJECTED';source:string;source_version:string;confidence:number;approved:boolean;approved_by:string|null;approved_at:string|null;evidence:{identity:FieldIdentity;source_hash:string;target_hash:string}}
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export function fieldIdentity(context:MemoryContext):FieldIdentity|undefined {const match=/^Compendium\.([-\w]+)\.([-\w]+)\.(Actor|Item|JournalEntry|RollTable|Scene|Macro|Cards|Playlist|Adventure)\.(\w{16})$/.exec(context.canonical_uuid||'');if(!match||!context.system||!context.canonical_version||!context.json_path?.length)return;return {system:context.system,package:match[1],pack:match[2],document_type:match[3],document_id:match[4],field_path:[...context.json_path],target_language:'es',version:context.canonical_version};}
export function canonicalEvidence(entry:Pick<MemoryEntry,'source_text'|'translated_text'|'translation_engine'|'approved'|'status'>&MemoryContext,at:string|null=null):CanonicalEvidence|undefined {const identity=fieldIdentity(entry);if(!identity)return;const verified=entry.approved&&entry.status==='APPROVED';return {schema_version:1,match_type:verified?'APPROVED_MANUAL':'CANONICAL_ID',decision:verified?'VERIFIED':entry.status==='REJECTED'?'REJECTED':'AMBIGUOUS',source:entry.translation_engine,source_version:identity.version,confidence:1,approved:verified,approved_by:verified?'LOCAL_USER':null,approved_at:verified?at:null,evidence:{identity,source_hash:hash(entry.source_text),target_hash:hash(entry.translated_text)}};}
export function validCanonicalEvidence(value:unknown):value is CanonicalEvidence {const v=value as CanonicalEvidence,i=v?.evidence?.identity;return Boolean(v?.schema_version===1&&['FOUNDRY_ID','UUID','CANONICAL_ID','EXACT_SOURCE','NORMALIZED_SOURCE','APPROVED_MANUAL','PDF_REFERENCE','FUZZY'].includes(v.match_type)&&['VERIFIED','HIGH_CONFIDENCE','AMBIGUOUS','REJECTED'].includes(v.decision)&&typeof v.source==='string'&&typeof v.source_version==='string'&&Number.isFinite(v.confidence)&&v.confidence>=0&&v.confidence<=1&&typeof v.approved==='boolean'&&(v.decision!=='VERIFIED'||v.approved)&&(!v.approved||v.decision==='VERIFIED'&&v.match_type!=='FUZZY'&&typeof v.approved_by==='string'&&!!v.approved_by&&typeof v.approved_at==='string'&&Number.isFinite(Date.parse(v.approved_at)))&&i&&['system','package','pack','document_type','document_id','version'].every(k=>typeof (i as any)[k]==='string')&&i.target_language==='es'&&/^\w{16}$/.test(i.document_id)&&Array.isArray(i.field_path)&&i.field_path.length>0&&i.field_path.every(p=>typeof p==='string'||Number.isSafeInteger(p))&&/^[a-f0-9]{64}$/.test(v.evidence.source_hash)&&/^[a-f0-9]{64}$/.test(v.evidence.target_hash));}
export function evidenceMatches(entry:MemoryEntry){const e=entry.canonical_evidence;if(!e)return true;return validCanonicalEvidence(e)&&e.approved&&e.decision==='VERIFIED'&&e.source_version===entry.canonical_version&&JSON.stringify(e.evidence.identity)===JSON.stringify(fieldIdentity(entry))&&e.evidence.source_hash===hash(entry.source_text)&&e.evidence.target_hash===hash(entry.translated_text);}
export function evidenceIntegrity(entry:MemoryEntry){const e=entry.canonical_evidence;if(!e)return true;return validCanonicalEvidence(e)&&e.approved===entry.approved&&(e.decision!=='VERIFIED'||e.approved)&&e.source_version===entry.canonical_version&&JSON.stringify(e.evidence.identity)===JSON.stringify(fieldIdentity(entry))&&e.evidence.source_hash===hash(entry.source_text)&&e.evidence.target_hash===hash(entry.translated_text);}
