import {sourceLanguage} from '../../src/services/translation/languageDetector';
import {MemoryStore,hashKey,compatible,type MemoryEntry,type CacheIdentity} from './store';import {fieldIdentity,canonicalEvidence,evidenceMatches} from './canonicalEvidence';
import {historicalContextMatches} from './historicalTrust';
import {reuseKey,reusable,cacheIdentity,estimatedSourceCalls} from '../translation/reuse';import {resolvePdfMemory} from './pdfResolution';import {PdfReuse} from './pdfReuse';import type {ProviderSettings} from '../contracts';import type {InventoryUnit} from '../translation/inventory';import {ProtectedContentEngine as P} from '../../src/services/protected-content/protectedContentEngine';
const add=(counts:Record<string,number>,reason:string,n=1)=>{counts[reason]=(counts[reason]||0)+n;};
export function cacheRejection(a:CacheIdentity,b:CacheIdentity){for(const [key,reason] of [['source_hash','CACHE_SOURCE_MISMATCH'],['source_language','CACHE_LANGUAGE_PAIR_MISMATCH'],['model','CACHE_MODEL_MISMATCH'],['provider','CACHE_PROVIDER_MISMATCH'],['prompt_version','CACHE_PROMPT_VERSION_MISMATCH'],['glossary_hash','CACHE_GLOSSARY_VERSION_MISMATCH'],['rules_version','CACHE_RULES_VERSION_MISMATCH'],['review_revision','CACHE_REVIEW_REVISION_MISMATCH'],['pdf_fingerprint','CACHE_PDF_FINGERPRINT_MISMATCH'],['context_hash','CACHE_CONTEXT_MISMATCH']] as const)if(a[key]!==b[key])return reason;return a.key===b.key?null:'CACHE_IDENTITY_HASH_MISMATCH';}
/** Independent populations and reason counts. Does not mutate memory or invoke providers. */
export async function auditReuse(store:MemoryStore,units:InventoryUnit[],settings:ProviderSettings,language:'auto'|'en'|'ru'='ru',terms:{source:string;target:string}[]=[],signal?:AbortSignal){
 const revision=store.revision;let prepared=0;
 const all=store.readEntries(),tm=all.filter(e=>!e.pdf),mappings=all.filter(e=>!e.historical&&e.reuse_scope!=='EXACT_SOURCE_ONLY'&&fieldIdentity(e)),approved=tm.filter(e=>e.approved),cache=store.readCache(),pdf=new PdfReuse(store),plan=resolvePdfMemory(store);
 const tmSources=new Map<string,MemoryEntry[]>(),ids=new Map<string,MemoryEntry[]>(),cacheSources=new Map<string,typeof cache[string][]>();
 for(const e of tm){const rows=tmSources.get(e.source_text)||[];rows.push(e);tmSources.set(e.source_text,rows);}for(const e of mappings){const id=fieldIdentity(e)!.document_id,rows=ids.get(id)||[];rows.push(e);ids.set(id,rows);}for(const row of Object.values(cache))if(row.identity){const rows=cacheSources.get(row.identity.source_hash)||[];rows.push(row);cacheSources.set(row.identity.source_hash,rows);}
 const canonical={mappings_loaded:mappings.length,candidates:0,verified:mappings.filter(e=>e.approved&&evidenceMatches(e)).length,usable:0,rejected:0,reasons:{} as Record<string,number>,unit_rejections:0,unit_reasons:{} as Record<string,number>,declared_ru_documents:0,demonstrable_ru_documents:0,fields_reusable:0};
 const memory={entries_loaded:tm.length,approved_entries:approved.length,EN_ES_entries:tm.filter(e=>e.source_language==='en').length,RU_ES_entries:tm.filter(e=>e.source_language==='ru').length,compatible_entries:0,exact_candidates:0,exact_hits:0,context_rejected:0,source_binding_unverified:0,rejected:0,reasons:{} as Record<string,number>,stage_diagnostics:{TM_NOT_APPROVED:tm.filter(e=>!e.approved).length,TM_LANGUAGE_PAIR_MISMATCH:language==='auto'?0:tm.filter(e=>e.source_language!==language).length}};
 const caches={legacy_cache_unverified:Object.keys(store.readLegacyCache()).length,entries_loaded:Object.keys(cache).length,legacy_without_metadata:Object.values(cache).filter(e=>!e.identity).length,compatible_entries:0,candidates:0,hits:0,rejected:0,unit_misses:0,unit_reasons:{} as Record<string,number>,reasons:{} as Record<string,number>};
 const glossary={entries_loaded:store.statistics().glossary_entries+terms.length,applicable_entries:0,fully_resolved_strings:0};
 const seen=new Set<string>(),compatibleTM=new Set<string>(),compatibleCache=new Set<string>(),usedCache=new Set<string>(),applicableTerms=new Set<string>(),ruDocs=new Set<string>(),verifiedDocs=new Set<string>(),reusedFields=new Set<string>(),references=new Map<string,{path:string;uuid:string}>(),stableIdentifiers=new Set<string>();
 for(const e of tm){if(!e.approved){memory.rejected++;add(memory.reasons,'TM_NOT_APPROVED');}else if(language!=='auto'&&e.source_language!==language){memory.rejected++;add(memory.reasons,'TM_LANGUAGE_PAIR_MISMATCH');}else if(e.rules_version!==P.rulesVersion){memory.rejected++;add(memory.reasons,'TM_RULES_VERSION_MISMATCH');}}
 for(const unit of units){signal?.throwIfAborted();if(++prepared%100===0)await new Promise<void>(resolve=>setImmediate(resolve));const lang=sourceLanguage(unit.source,language)||'unknown',key=reuseKey(store,settings,unit.source,lang,unit.context,terms);if(seen.has(key))continue;seen.add(key);if(lang==='unknown'){add(memory.reasons,'SOURCE_LANGUAGE_UNCERTAIN');continue;}
  const c=unit.context,identity=fieldIdentity(c);if(identity&&/[\u0400-\u04ff]/.test(unit.source))ruDocs.add(c.canonical_uuid!);
  for(const ref of unit.identity_evidence?.explicit_references||[])references.set(JSON.stringify([unit.file,ref]),ref);for(const id of unit.identity_evidence?.system_identifiers||[])stableIdentifiers.add(JSON.stringify([unit.file,id]));
  const sourceRows=tmSources.get(unit.source)||[],historicalLookup=store.historicalLookup(unit.source,lang,c);if(historicalLookup.candidates&&!historicalLookup.entry){if(historicalLookup.reason==='TM_CONTEXT_MISMATCH')memory.context_rejected++;if(historicalLookup.reason==='TM_SOURCE_BINDING_UNVERIFIED')memory.source_binding_unverified++;}
  const compatibleRows=sourceRows.filter(e=>e.source_language===lang&&(e.historical?historicalContextMatches(e,c):compatible(e,c)&&(!c.canonical_uuid||JSON.stringify(e.json_path)===JSON.stringify(c.json_path))));for(const e of compatibleRows)compatibleTM.add(e.id);if(compatibleRows.length)memory.exact_candidates++;
  const tmHit=approved.length?store.exact(unit.source,lang,c):undefined;if(tmHit&&reusable(unit.source,tmHit.translated_text,c)&&!store.originalRequested(unit.source,lang,c)&&!store.rejected(unit.source,tmHit.translated_text,lang,c))memory.exact_hits++;
  const canonicalHit=canonical.verified?store.canonical(c)||pdf.canonical(unit.source,c):undefined;
  if(canonicalHit&&reusable(unit.source,canonicalHit.translated_text,c)&&!store.originalRequested(unit.source,lang,c)&&!store.rejected(unit.source,canonicalHit.translated_text,lang,c)){canonical.usable++;reusedFields.add(key);if(/[\u0400-\u04ff]/.test(unit.source))verifiedDocs.add(c.canonical_uuid!);}
  let reason:string|undefined;
  if(!identity)reason='CANONICAL_ID_NOT_FOUND';else {
   const rows=ids.get(identity.document_id)||[];const pkg=rows.filter(e=>fieldIdentity(e)!.package===identity.package&&fieldIdentity(e)!.pack===identity.pack);const type=pkg.filter(e=>fieldIdentity(e)!.document_type===identity.document_type);const system=type.filter(e=>e.system===identity.system);const field=system.filter(e=>JSON.stringify(e.json_path)===JSON.stringify(identity.field_path));const version=field.filter(e=>e.canonical_version===identity.version);
   if(!rows.length)reason='CANONICAL_ID_NOT_FOUND';else if(!pkg.length)reason='CANONICAL_PACK_MISMATCH';else if(!type.length)reason='CANONICAL_DOCUMENT_TYPE_MISMATCH';else if(!system.length)reason='CANONICAL_SYSTEM_MISMATCH';else if(!field.length)reason='CANONICAL_FIELD_MISMATCH';else if(!version.length)reason='CANONICAL_SOURCE_VERSION_MISMATCH';else{canonical.candidates++;if(!canonicalHit||!reusable(unit.source,canonicalHit.translated_text,c)){const trusted=version.filter(e=>e.approved);reason=!trusted.length?'CANONICAL_TRANSLATION_NOT_APPROVED':new Set(trusted.map(e=>e.translated_text)).size>1?'CANONICAL_CONFLICT':trusted.some(e=>!evidenceMatches(e))?'CANONICAL_EVIDENCE_INVALID':'CANONICAL_VALIDATION_FAILED';}}
  }
  if(reason){canonical.unit_rejections++;add(canonical.unit_reasons,reason);}
  const descriptor=cacheIdentity(store,settings,unit.source,lang,c,terms),cached=store.getCache(key,descriptor),related=cacheSources.get(descriptor.source_hash)||[];
  if(cached!==undefined){caches.candidates++;compatibleCache.add(key);usedCache.add(key);if(reusable(unit.source,cached,c)&&!store.originalRequested(unit.source,lang,c)&&!store.rejected(unit.source,cached,lang,c))caches.hits++;else{caches.unit_misses++;add(caches.unit_reasons,'CACHE_VALIDATION_FAILED');}}
  else{caches.unit_misses++;if(related.length){caches.candidates++;for(const row of related){const reason=cacheRejection(row.identity!,descriptor);if(reason)add(caches.unit_reasons,reason);}}else add(caches.unit_reasons,'CACHE_KEY_NOT_PRESENT');}
  const scoped=[...store.glossary(c),...terms];for(const term of scoped)applicableTerms.add(hashKey(term));const prose=P.protect(unit.source).protectedText.replace(/\[\[PROTECTED_\d+\]\]/g,'').trim();if(prose&&estimatedSourceCalls(settings,unit.source,scoped)===0)glossary.fully_resolved_strings++;
 }
 for(const [key,row] of Object.entries(cache))if(!usedCache.has(key)){caches.rejected++;add(caches.reasons,!row.identity?'LEGACY_CACHE_UNVERIFIED':'CACHE_NO_MATCHING_SOURCE_OR_CONTEXT');}
 for(const e of mappings)if(!e.approved||!evidenceMatches(e)){canonical.rejected++;add(canonical.reasons,!e.approved?'CANONICAL_TRANSLATION_NOT_APPROVED':'CANONICAL_EVIDENCE_INVALID');}
 for(const e of approved)if(e.source_language===(language==='auto'?e.source_language:language)&&e.rules_version===P.rulesVersion&&!compatibleTM.has(e.id)){memory.rejected++;add(memory.reasons,'TM_CONTEXT_MISMATCH');}
 memory.compatible_entries=compatibleTM.size;caches.compatible_entries=compatibleCache.size;glossary.applicable_entries=applicableTerms.size;canonical.declared_ru_documents=ruDocs.size;canonical.demonstrable_ru_documents=verifiedDocs.size;canonical.fields_reusable=reusedFields.size;
 if(store.revision!==revision)throw new Error('MEMORY_REVISION_CONFLICT');signal?.throwIfAborted();
 const historical=all.filter(e=>e.historical),histGroups=new Set(historical.map(e=>hashKey([e.source_text,e.historical!.context])));
 return {historical:{babele_entries_loaded:historical.length,babele_unique_groups:histGroups.size,babele_approved_entries:historical.filter(e=>e.approved).length,babele_context_required:historical.filter(e=>e.historical!.reuse_policy==='CONTEXT_REQUIRED').length,babele_conflicts:new Set(historical.filter(e=>e.historical!.reuse_policy==='CONFLICT'&&e.status!=='REJECTED').map(e=>hashKey([e.source_text,e.historical!.context]))).size},schema_version:1,mode:'READ_ONLY_NO_INFERENCE',count_policy:'Independent entry/unique-unit populations; stage_diagnostics overlap and do not sum to rejected. Pipeline priority counters are reported separately.',canonical,translation_memory:memory,cache:caches,pdf:{candidates:plan.candidates,groups:plan.groups_total,variants:plan.candidates,duplicate_variants:plan.duplicates,verified:plan.counts.VERIFIED,high_confidence:plan.counts.HIGH_CONFIDENCE,ambiguous:plan.counts.AMBIGUOUS,rejected:plan.counts.REJECTED},glossary,identity_discovery:{explicit_references:references.size,compendium_references:[...references.values()].filter(r=>r.uuid.startsWith('Compendium.')).length,world_references:[...references.values()].filter(r=>!r.uuid.startsWith('Compendium.')).length,system_identifiers:stableIdentifiers.size,policy:'ID/UUID scoped by system, pack, document type, version and field. World IDs and unversioned aliases never authorize reuse.'},mapping_records:mappings.map(e=>({memory_id:e.id,...(e.canonical_evidence||canonicalEvidence(e,e.feedback?.at||e.updated_at))}))};
}
