import React,{useCallback,useEffect,useState} from 'react';
import { Check,Search,RefreshCw,ShieldCheck } from 'lucide-react';
import type { MemoryEntry,ReviewAction } from '../../desktop/memory/store';
import type { ReviewEntry } from '../../desktop/memory/review';
import type { MemoryConflict } from '../../desktop/memory/conflicts';
import type {PdfBindingPreview} from '../../desktop/memory/pdfAlignment';
import type {PdfSegment} from '../../desktop/memory/pdfCorpus';
import type {ResolutionClass} from '../../desktop/memory/pdfResolution';

const statusName={CANDIDATE:'Por revisar',APPROVED:'Aprobada',REJECTED:'Rechazada'};
export function TranslationReview(){
  const [resolution,setResolution]=useState<'ALL'|ResolutionClass>('ALL'),[resolutionInfo,setResolutionInfo]=useState<Awaited<ReturnType<typeof window.desktop.listMemory>>['resolution']>();
  const [pdfQueries,setPdfQueries]=useState({en:'',es:''}),[pdfResults,setPdfResults]=useState<{en:PdfSegment[];es:PdfSegment[]}>({en:[],es:[]}),[pdfSelection,setPdfSelection]=useState({en:'',es:''});
  const [query,setQuery]=useState(''),[status,setStatus]=useState<'ALL'|MemoryEntry['status']>('ALL'),[offset,setOffset]=useState(0);
  const [source,setSource]=useState<'ALL'|'PDF'>('ALL'),[binding,setBinding]=useState<PdfBindingPreview|null>(null),[bindingField,setBindingField]=useState('');
  const [entries,setEntries]=useState<ReviewEntry[]>([]),[conflicts,setConflicts]=useState<MemoryConflict[]>([]),[revision,setRevision]=useState(0),[total,setTotal]=useState(0);
  const [selectedId,setSelectedId]=useState(''),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const selected=entries.find(entry=>entry.id===selectedId);
  const load=useCallback(async()=>{
    setLoading(true);
    try{
      const [page,groups]=await Promise.all([window.desktop.listMemory({query,status,source,resolution,offset,limit:50}),window.desktop.memoryConflicts()]);
      setResolutionInfo(page.resolution);
      setEntries(page.entries);setTotal(page.total);setRevision(page.revision);setConflicts(groups.conflicts);setError('');
    }catch{setError('No se pudo cargar la memoria.');}finally{setLoading(false);}
  },[query,status,source,resolution,offset]);
  useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{if(active)void load();},180);return()=>{active=false;window.clearTimeout(timer);};},[load]);
  useEffect(()=>{setDraft(selected?.translated_text||'');setBinding(null);},[selectedId,selected?.translated_text]);
  const review=async(action:ReviewAction)=>{
    if(!selected)return;setBusy(true);setError('');setMessage('');
    try{
      const result=await window.desktop.reviewMemory({id:selected.id,action,revision,translatedText:action==='EDIT'?draft:undefined});
      setSelectedId(result.id);await load();setMessage(action==='EDIT'?'Edición guardada como candidata. Revísala y acéptala para reutilizarla.':action==='RESTORE'?'Se conservará el original en futuras copias de este contexto.':'Revisión guardada.');
    }catch{setError('No se pudo guardar. Comprueba los tokens y la calidad, actualiza la lista y espera si hay una traducción activa.');}finally{setBusy(false);}
  };
  const conflict=selected&&conflicts.find(group=>group.variants.some(variant=>variant.id===selected.id));
  return <section className="space-y-4">
    <div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">Memoria y revisión</h1><p className="text-sm text-slate-400 mt-1">Aprueba traducciones por contexto para reutilizarlas con confianza.</p></div><button className="secondary-action" disabled={busy||loading} onClick={()=>void load()}><RefreshCw size={14}/>Actualizar</button></div>
    <p className="text-xs text-slate-400 flex gap-2 items-center"><ShieldCheck size={14}/>Las decisiones se guardan en tu memoria local. Las copias ya generadas se conservan.</p>
    <div className="flex flex-wrap gap-2 items-center"><select aria-label="Fuente de memoria" value={source} disabled={busy} onChange={event=>{setSource(event.target.value as typeof source);setOffset(0);}} className="bg-slate-900 rounded-lg border border-slate-700 px-3 py-2 text-sm"><option value="ALL">Todas las fuentes</option><option value="PDF">SRD PDF</option></select><button className="secondary-action" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await window.desktop.generatePdfMemory();setSource('PDF');setOffset(0);setMessage(`${result.new_entries} propuestas nuevas. Ninguna se aprobó automáticamente.`);await load();}catch{setError('No se pudo preparar el SRD. Comprueba los PDFs verificados y su extracción.');}finally{setBusy(false);}}}>Preparar propuestas SRD</button><span className="text-xs text-slate-400">La fuente está verificada; revisa la correspondencia EN→ES antes de aceptar.</span></div>
    <div className="flex flex-wrap gap-2"><label className="flex flex-1 min-w-48 items-center gap-2 rounded-lg border border-slate-700 px-3"><Search size={15}/><input aria-label="Buscar en memoria" value={query} onChange={event=>{setQuery(event.target.value);setOffset(0);}} className="w-full bg-transparent py-2 text-sm outline-none" placeholder="Texto, sistema o módulo"/></label><select aria-label="Estado de memoria" value={status} disabled={busy} onChange={event=>{setStatus(event.target.value as typeof status);setOffset(0);}} className="bg-slate-900 rounded-lg border border-slate-700 px-3 text-sm"><option value="ALL">Todas</option><option value="CANDIDATE">Por revisar</option><option value="APPROVED">Aprobadas</option><option value="REJECTED">Rechazadas</option></select></div>
    {!!conflicts.length&&<p className="text-sm text-amber-300">{conflicts.length} contextos con variantes pendientes de revisión. Selecciona una entrada para ver sus alternativas.</p>}
    <details className="rounded-lg border border-slate-700 p-3"><summary className="cursor-pointer text-sm">Elegir correspondencia EN → ES en el SRD</summary><p className="text-xs text-slate-400 my-2">Selecciona fragmentos equivalentes. Se guardarán como candidatos, pendientes de aprobación.</p><div className="grid gap-3 lg:grid-cols-2">{(['en','es'] as const).map(language=><div key={language} className="space-y-2"><label className="block text-xs">Buscar {language.toUpperCase()}<input value={pdfQueries[language]} disabled={busy} onChange={event=>setPdfQueries({...pdfQueries,[language]:event.target.value})} className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2"/></label><button className="secondary-action" disabled={busy||pdfQueries[language].trim().length<2} onClick={async()=>{setBusy(true);try{const rows=await window.desktop.searchPdfSegments(pdfQueries[language],language);setPdfResults(previous=>({...previous,[language]:rows}));setPdfSelection(previous=>({...previous,[language]:''}));}catch{setError('No se pudo consultar el corpus verificado.');}finally{setBusy(false);}}}>Buscar fragmentos</button><div className="max-h-48 overflow-auto">{pdfResults[language].map(row=><label key={row.id} className="block p-2 text-xs border-b border-slate-800"><input type="radio" name={`pdf-${language}`} disabled={busy} checked={pdfSelection[language]===row.id} onChange={()=>setPdfSelection({...pdfSelection,[language]:row.id})}/> Página {row.page} · {row.kind}<p className="whitespace-pre-wrap mt-1">{row.text}</p></label>)}</div></div>)}</div><button className="secondary-action mt-3" disabled={busy||!pdfSelection.en||!pdfSelection.es} onClick={async()=>{setBusy(true);try{const result=await window.desktop.createPdfAlignment(pdfSelection.en,pdfSelection.es);setSource('PDF');setOffset(0);setSelectedId(result.id);await load();setMessage('Correspondencia guardada como candidata. Revísala antes de aceptar.');}catch{setError('Los fragmentos no tienen un formato compatible o la fuente cambió.');}finally{setBusy(false);}}}>Crear candidata EN → ES</button></details>
    {resolutionInfo&&<div className="rounded-lg border border-slate-700 p-3 text-xs space-y-2"><p>{resolutionInfo.groups} grupos · {resolutionInfo.duplicates} variantes repetidas. Verificación y confianza se distinguen de aprobación.</p><p>{Object.entries(resolutionInfo.counts).map(([key,value])=>`${key}: ${value}`).join(' · ')}</p><select aria-label="Confianza de correspondencia" value={resolution} disabled={busy} onChange={event=>{setResolution(event.target.value as typeof resolution);setOffset(0);}} className="bg-slate-900 p-2 rounded-lg"><option value="ALL">Todas las correspondencias</option>{(['VERIFIED','HIGH_CONFIDENCE','AMBIGUOUS','REJECTED'] as const).map(value=><option key={value} value={value}>{value}</option>)}</select><button className="secondary-action ml-2" disabled={busy||!resolutionInfo.auto_approvable} onClick={async()=>{setBusy(true);try{const result=await window.desktop.approveVerifiedPdf(resolutionInfo.input_hash);await load();setMessage(`${result.approved} correspondencias verificadas aprobadas por evidencia existente.`);}catch{setError('La evidencia cambió. Actualiza antes de resolver.');}finally{setBusy(false);}}}>Resolver verificadas ({resolutionInfo.auto_approvable})</button></div>}
    {source==='PDF'&&<button className="secondary-action" disabled={busy} onClick={async()=>{setBusy(true);try{const result=await window.desktop.resolveCanonicalPdf();if(result){await load();setMessage(`${result.approved} vínculos canónicos aprobados con identidad completa y pareja SRD previamente aprobada.`);}}catch{setError('No se pudieron resolver vínculos. Comprueba identidad, evidencia y estado de la memoria.');}finally{setBusy(false);}}}>Resolver vínculos canónicos verificados</button>}
    <div className="grid gap-3 lg:grid-cols-2">
      <div className="rounded-xl border border-slate-800 overflow-hidden"><div className="px-3 py-2 text-xs text-slate-400 border-b border-slate-800">{total} entradas · {loading?'Cargando…':'Memoria privada'}</div><div className="max-h-[520px] overflow-auto">
        {entries.map(entry=><button key={entry.id} disabled={busy} onClick={()=>{setSelectedId(entry.id);setMessage('');}} className={`block w-full text-left p-3 border-b border-slate-800 ${selectedId===entry.id?'bg-indigo-500/10':'hover:bg-slate-800/40'}`}><div className="flex gap-2 justify-between"><span className="text-sm truncate">{entry.source_text}</span><span className="text-xs text-slate-400 shrink-0">{entry.original_requested?'Original elegido':statusName[entry.status]}</span></div><p className="text-xs text-slate-400 truncate mt-1">{entry.translated_text}</p><p className="text-[11px] text-slate-500 mt-1">{[entry.system,entry.module,entry.document_type,entry.field_type].filter(Boolean).join(' · ')||'Contexto general'}</p></button>)}
        {!entries.length&&!loading&&<p className="p-5 text-sm text-slate-400">No hay entradas para esta búsqueda. Las traducciones validadas aparecerán aquí como candidatas.</p>}
      </div><div className="flex items-center justify-between p-2 text-xs"><button className="secondary-action" disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Anterior</button><span>{total?`${offset+1}–${Math.min(offset+50,total)}`:'0'}</span><button className="secondary-action" disabled={busy||offset+50>=total} onClick={()=>setOffset(offset+50)}>Siguiente</button></div></div>
      <div className="rounded-xl border border-slate-800 p-4 space-y-3">
        {selected?<><div className="flex justify-between gap-2"><strong className="text-sm">Revisar traducción</strong><span className="text-xs text-slate-400">{selected.source_language.toUpperCase()} → ES · {statusName[selected.status]}</span></div><label className="block text-xs text-slate-400">Original<textarea aria-label="Texto original de memoria" readOnly value={selected.source_text} className="w-full mt-1 min-h-28 bg-slate-950 border border-slate-700 rounded-lg p-2 text-sm text-slate-200"/></label><label className="block text-xs text-slate-400">Traducción<textarea aria-label="Editar traducción de memoria" disabled={busy} value={draft} onChange={event=>setDraft(event.target.value)} className="w-full mt-1 min-h-28 bg-slate-950 border border-slate-700 rounded-lg p-2 text-sm text-slate-200"/></label><p className="text-xs text-slate-500">{selected.translation_engine} · {selected.model||'sin modelo'} · usada en {selected.times_used} ejecuciones limpias</p>
        {selected.original_requested&&<p role="status" className="text-xs text-amber-200">Se conservará el original en futuras copias. Aceptar una variante vuelve a habilitar su traducción.</p>}
        {selected.surrounding_context&&<p className="text-xs text-slate-400 whitespace-pre-wrap">Contexto: {selected.surrounding_context}</p>}
        {selected.pdf&&<div className="rounded-lg border border-indigo-500/30 p-3 text-xs text-slate-300 space-y-2"><p>SRD 5.2.1 · Ámbito: D&D5e, {selected.pdf.kind==='heading'?'nombres':'descripciones'}. Coincidencia exacta; las aproximadas solo aportan contexto.</p><p>EN: {selected.pdf.source.document} · página {selected.pdf.source.page} · {selected.pdf.source.segment}</p><p>ES: {selected.pdf.target.document} · página {selected.pdf.target.page} · {selected.pdf.target.segment}</p><p>Propuesta estructural, sin aprobación automática. Comprueba significado y contexto en ambas páginas.</p>{selected.pdf.edited&&<p>Texto editado manualmente; conserva la referencia del PDF original.</p>}
          {selected.pdf.binding?<><p>Vínculo Foundry: {selected.canonical_uuid} · versión {selected.canonical_version} · {JSON.stringify(selected.json_path)}</p><p>Uso: {selected.pdf.binding.usage==='CONTEXT_ONLY'?'solo contexto para IA; conserva la estructura original':'reutilización exacta validada'}</p><label>Texto completo del documento<textarea readOnly aria-label="Texto Foundry del vínculo" value={selected.pdf.binding.source_text||selected.pdf.binding.source_excerpt} className="w-full min-h-28 mt-1 bg-slate-950 rounded-lg border border-slate-700 p-2"/></label><p>Aceptar también confirma esta correspondencia. Un cambio de texto, versión o campo invalida el vínculo.</p></>:selected.approved&&<button className="secondary-action" disabled={busy} onClick={async()=>{setBusy(true);try{const preview=await window.desktop.preparePdfBinding(selected.id);setBinding(preview);setBindingField(preview?.fields[0]?.id||'');}catch{setError('No se encontró un campo Foundry compatible para vincular.');}finally{setBusy(false);}}}>Vincular a documento Foundry</button>}
          {binding&&<div className="space-y-2"><p>{binding.file}</p><select aria-label="Campo Foundry del vínculo" value={bindingField} onChange={event=>setBindingField(event.target.value)} className="w-full bg-slate-900 rounded-lg border border-slate-700 p-2">{binding.fields.map(field=><option key={field.id} value={field.id}>{JSON.stringify(field.path)}</option>)}</select><textarea readOnly aria-label="Texto completo antes de vincular" value={binding.fields.find(field=>field.id===bindingField)?.source_text||''} className="w-full min-h-28 bg-slate-950 rounded-lg border border-slate-700 p-2"/><button className="secondary-action" disabled={busy||!bindingField} onClick={async()=>{setBusy(true);try{const result=await window.desktop.commitPdfBinding(binding.token,bindingField);setBinding(null);setSelectedId(result.id);await load();setMessage('Vínculo guardado como candidato. Revísalo y acéptalo para habilitar RU→ES.');}catch{setBinding(null);setError('El documento o la revisión cambiaron. Prepara el vínculo nuevamente.');}finally{setBusy(false);}}}>Crear vínculo para revisión</button><button className="secondary-action" disabled={busy} onClick={()=>setBinding(null)}>Descartar vínculo</button></div>}
        </div>}
        {conflict&&<div className="rounded-lg bg-amber-500/10 p-3 text-xs text-amber-200"><strong>{conflict.approved_conflict?'Conflicto entre aprobadas':'Variantes en el mismo contexto'}</strong><ul className="mt-2 space-y-1">{conflict.variants.map(variant=><li key={variant.id}>{variant.target} · {statusName[variant.status]}</li>)}</ul><p className="mt-2">Resolver selecciona esta variante y rechaza las alternativas de este contexto.</p></div>}
        <div className="flex flex-wrap gap-2"><button className="primary-action" disabled={busy||draft!==selected.translated_text} onClick={()=>void review('ACCEPT')}><Check size={14}/>Aceptar</button><button className="secondary-action" disabled={busy||draft===selected.translated_text} onClick={()=>void review('EDIT')}>Guardar edición</button><button className="secondary-action" disabled={busy} onClick={()=>void review('REJECT')}>Rechazar</button><button className="secondary-action" disabled={busy} onClick={()=>void review('RESTORE')}>Restaurar original</button>{conflict&&<button className="secondary-action" disabled={busy||draft!==selected.translated_text} onClick={()=>void review('RESOLVE')}>Usar esta variante en este contexto</button>}</div></>:<p className="text-sm text-slate-400">Selecciona una entrada para comparar, editar o aprobar su traducción. Los tokens y las referencias deben conservarse exactamente.</p>}
      </div>
    </div>
    {message&&<p role="status" className="text-sm text-emerald-300">{message}</p>}{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}
  </section>;
}
