import {afterEach,expect,it,vi} from 'vitest';import fs from 'node:fs/promises';import path from 'node:path';
import {pdfFixture} from '../memory/pdfFixtures';import {bindPdfAlignment} from '../../desktop/memory/pdfAlignment';import {runLoggedBatch} from '../../desktop/logging/runReport';import {providers} from '../../desktop/providers';import {jsonQualityGate} from '../../src/services/validation/qualityGate';
const roots:string[]=[];afterEach(async()=>{vi.restoreAllMocks();for(const root of roots.splice(0))await fs.rm(root,{recursive:true,force:true});});
it.each(['en','ru'] as const)('PDF golden %s preserves native structure/HTML/UUID/rolls and reports real reuse origin',async language=>{
 const fixture=await pdfFixture();roots.push(fixture.root);const {store,pair,moduleRoot,root}=fixture;
 const input=await fs.readFile(path.resolve('tests/golden/foundry_v14_368/pdf-memory',language,'input.json'),'utf8'),expected=JSON.parse(await fs.readFile(path.resolve('tests/golden/foundry_v14_368/pdf-memory',language,'expected.json'),'utf8'));
 const file='packs/items/_source/sword.json';await fs.writeFile(path.join(moduleRoot,file),input);await store.approve(await pair());await store.approve(await pair(2));
 if(language==='ru'){const binding=await bindPdfAlignment(store,store.readEntries().find(entry=>entry.source_text==='Longsword')!.id,moduleRoot,file,['name']);await store.approve(binding.id);}
 const spy=vi.spyOn(providers.ollama,'translate').mockImplementation(async(_settings,request)=>{request.telemetry?.('ollama_requests');return request.texts.map(text=>text.replace('Make an attack roll against','Realiza una tirada de ataque contra').replace('and use','y usa').replace('Совершите бросок атаки против','Realiza una tirada de ataque contra').replace('и используйте','y usa'));});
 let report='';const output=path.join(root,'output');const result=await runLoggedBatch(moduleRoot,output,{endpoint:'http://127.0.0.1:11500',model:'translategemma:27b',thermalEnabled:false},store,path.join(root,'logs'),new AbortController().signal,()=>{},language,'pdf-golden',[],directory=>{report=directory;});
 expect(result.state).toBe('COMPLETED');expect(spy).toHaveBeenCalledOnce();const translated=await fs.readFile(path.join(output,file),'utf8');expect(JSON.parse(translated)).toEqual(expected);expect(jsonQualityGate(input,translated,[['name'],['system','description','value']]).status).toBe('PASS');expect(await fs.readFile(path.join(moduleRoot,file),'utf8')).toBe(input);
 const summary=JSON.parse(await fs.readFile(path.join(report,'summary.json'),'utf8'));expect(summary.metrics[language==='en'?'pdf_exact_hits':'pdf_canonical_hits']).toBe(1);expect(summary.metrics.ollama_requests).toBe(1);expect(summary.pdf_memory.approved_alignments).toBeGreaterThan(0);expect(summary.translation_provenance.some((unit:any)=>unit.origins.includes(language==='en'?'PDF_EXACT':'PDF_CANONICAL'))).toBe(true);expect(summary.translation_provenance.every((unit:any)=>!unit.source_text&&!unit.pdf?.binding?.source_excerpt)).toBe(true);
});
