import {it,expect,afterEach,vi} from 'vitest';import fs from 'node:fs/promises';
import {pdfFixture} from '../memory/pdfFixtures';import {TranslationRuntime} from '../../desktop/translation/runtime';import {providers} from '../../desktop/providers';import {reuseKey,cacheIdentity} from '../../desktop/translation/reuse';import {ProtectedContentEngine as P} from '../../src/services/protected-content/protectedContentEngine';
import {jsonQualityGate} from '../../src/services/validation/qualityGate';
const roots:string[]=[];afterEach(async()=>{vi.restoreAllMocks();for(const root of roots.splice(0))await fs.rm(root,{recursive:true,force:true});});
it('reconciles canonical, PDF, exact memory, cache, glossary and model while preserving native invariants',async()=>{
 const {root,store,pair}=await pdfFixture();roots.push(root);const settings={endpoint:'http://127.0.0.1:11500',model:'translategemma:27b',thermalEnabled:false};
 const context={system:'dnd5e',module:'test',document_type:'weapon',field_type:'name'};
 const canonical={...context,canonical_uuid:'Compendium.test.items.Item.abcdefghijklmnop',canonical_version:'1',json_path:['name']};
 await store.approve(await store.candidate('Sword','Espada','en',canonical,'manual',''));await store.approve(await pair());await store.approve(await store.candidate('Shield','Escudo','en',context,'manual',''));await store.setGlossary([{source:'Armor Class',target:'Clase de Armadura',version:'1',system:'dnd5e'}]);await store.cache(reuseKey(store,settings,'Dagger','en',context,[]),'Daga',cacheIdentity(store,settings,'Dagger','en',context,[]));
 const spy=vi.spyOn(providers.ollama,'translate').mockImplementation(async(_s,r)=>r.texts.map(t=>t.replace('Make an attack roll','Realiza una tirada de ataque')));
 const runtime=new TranslationRuntime(store,settings),sources=['Меч','Longsword','Shield','Dagger','Armor Class','<p>Make an attack roll @UUID[Item.target] [[/r 1d20+5]].</p>'],contexts=[canonical,context,context,context,context,{...context,field_type:'description.value'}];
 const results:string[]=[];for(let i=0;i<sources.length;i++){const [wire]=await runtime.translate({sourceLanguage:i===0?'ru':'en',texts:[P.protect(sources[i]).protectedText],units:[{sourceText:sources[i],context:contexts[i]}]});results.push(P.restore(wire,P.protect(sources[i]).tokens).restoredText);}
 expect(results.slice(0,5)).toEqual(['Espada','Espada larga','Escudo','Daga','Clase de Armadura']);expect(spy).toHaveBeenCalledOnce();expect(runtime.metrics.values.canonical_hits).toBe(1);expect(runtime.metrics.values.pdf_exact_hits).toBe(1);expect(runtime.metrics.values.tm_exact_hits).toBe(1);expect(runtime.metrics.values.cache_hits).toBe(1);
 const original={_id:'abcdefghijklmnop',uuid:'Compendium.test.items.Item.abcdefghijklmnop',icon:'icons/sword.webp',values:[1,2,{formula:'1d20+5'}],items:sources.map((name,i)=>({_id:String(i).padStart(16,'0'),name}))};const translated={...original,items:original.items.map((item,i)=>({...item,name:results[i]}))};expect(jsonQualityGate(JSON.stringify(original),JSON.stringify(translated),sources.map((_s,i)=>['items',i,'name'])).status).toBe('PASS');expect(translated.values).toEqual(original.values);expect(translated._id).toBe(original._id);
});
