import fs from 'node:fs/promises';import path from 'node:path';import {MemoryStore,hashKey} from '../desktop/memory/store';import {pdfHash} from '../desktop/memory/pdfCorpus';import {auditReuse} from '../desktop/memory/reuseAudit';import {inventory} from '../desktop/translation/inventory';import {translationPreflight} from '../desktop/translation/preflight';
import {auditHistoricalBabele} from '../desktop/memory/historicalBabeleImport';
import {canonicalResolution} from '../desktop/memory/canonicalResolution';
import {PdfReuse} from '../desktop/memory/pdfReuse';
import {auditSrdIdentities} from '../desktop/memory/srdIdentityAudit';
import {TranslationRuntime} from '../desktop/translation/runtime';
import {ProtectedContentEngine as P} from '../src/services/protected-content/protectedContentEngine';
const root=process.argv[2]||'C:/Users/leond/AppData/Local/FoundryVTT/Data/modules/fifthpendium',directory=path.resolve(process.env.APPDATA||'','foundry-translator/translation-memory'),database=path.join(directory,'store.json'),before=pdfHash(await fs.readFile(database)),store=await new MemoryStore(directory).load();
let settings={endpoint:'http://127.0.0.1:11500',model:'translategemma:27b'};try{settings=JSON.parse(await fs.readFile(path.join(directory,'../provider.json'),'utf8'));}catch{}
const data=await inventory(root),audit=await auditReuse(store,data.units,settings,'ru');
const historicalRoot=process.argv[3]||'C:/Users/leond/OneDrive/Escritorio/spanish';
const historical=await auditHistoricalBabele(historicalRoot,data.units,store),bridge=canonicalResolution(store,data.units),pdfReuse=new PdfReuse(store).statistics();
const srdInventory={srd_es_entries_loaded:[...store.pdfCorpus.segments.values()].filter(s=>s.language==='es').length,srd_en_entries_loaded:[...store.pdfCorpus.segments.values()].filter(s=>s.language==='en').length,srd_en_es_links:pdfReuse.approved_alignments,ru_to_srd_verified_links:pdfReuse.canonical_bindings,ru_to_srd_pending_links:bridge.verified_bindings,ru_to_srd_historical_candidates:bridge.mapped_units,ru_to_srd_conflicting_candidates:bridge.conflicting_units,ru_to_srd_missing_approved_alignment:bridge.missing_approved_alignment,reason:pdfReuse.approved_alignments?'APPROVED_ALIGNMENT_AVAILABLE':'SRD_BILINGUAL_ALIGNMENT_NOT_VERIFIED',entry_definition:'Sealed SRD eligible segments and heading lines; excludes Player Handbook. Document verification does not verify bilingual pairs.'};
await fs.mkdir('reports/canonical-memory',{recursive:true});await fs.writeFile('reports/canonical-memory/audit-before-mappings.json',JSON.stringify({...audit,memory_sha256:before,source_fingerprint:hashKey(data.fingerprints)},null,2));
console.log(JSON.stringify({stage:'INDEPENDENT_AUDIT',canonical:audit.canonical,tm:audit.translation_memory,cache:audit.cache,pdf:audit.pdf,glossary:audit.glossary,identity:audit.identity_discovery}));
const preflight=await translationPreflight(root,'ru',store,settings,[],undefined,{offline:true});
const after=await inventory(root);if(before!==pdfHash(await fs.readFile(database))||hashKey(data.fingerprints)!==hashKey(after.fingerprints))throw new Error('DRY_RUN_INPUT_CHANGED');
if(historical.source_fingerprint!==(await auditHistoricalBabele(historicalRoot,data.units,store)).source_fingerprint)throw new Error('HISTORICAL_SOURCE_CHANGED');
const canonical=preflight.canonical_candidates+preflight.pdf_canonical_candidates,srd=preflight.pdf_canonical_candidates+preflight.pdf_exact_candidates;
const resolved=preflight.strings_unique-preflight.strings_requiring_ai;
const report={schema_version:2,mode:'OFFLINE_DRY_RUN_NO_OLLAMA_NO_BENCHMARK',FILES:{files_discovered:preflight.files},STRINGS:{strings_detected:preflight.strings_translatable,strings_unique:preflight.strings_unique},REUSE:{canonical_hits:canonical,srd_hits:srd,manual_approved_hits:preflight.manual_approved_hits,tm_exact_hits:preflight.exact_tm_candidates,cache_hits:preflight.cache_candidates,glossary_full_hits:preflight.glossary_only_hits},PDF:audit.pdf,AI:{strings_requiring_model:preflight.strings_requiring_ai,estimated_chunks:preflight.estimated_model_calls,estimated_model_requests:preflight.estimated_model_calls},KPI:{strings_resolved_without_AI:resolved,strings_resolved_by_approved_reuse:canonical+preflight.pdf_exact_candidates+preflight.exact_tm_candidates+preflight.cache_candidates+preflight.glossary_only_hits,protected_only_strings:preflight.protected_only_strings,original_choices:preflight.original_choices,AI_avoidance_rate:resolved/Math.max(1,preflight.strings_unique)},comparison:{before:{strings_unique:29348,strings_requiring_model:28372,estimated_model_requests:33942},after:{strings_unique:preflight.strings_unique,strings_requiring_model:preflight.strings_requiring_ai,estimated_model_requests:preflight.estimated_model_calls},strings_removed_from_AI:28372-preflight.strings_requiring_ai,estimated_requests_eliminated:33942-preflight.estimated_model_calls,same_denominator:preflight.strings_unique===29348,scope_change_policy:'Noncanonical units now retain manifest pack scope to prevent unsafe cross-pack deduplication'},warnings:preflight.warnings,skipped_files:preflight.skipped_files,approved_production_mappings:audit.canonical.verified,real_sanity_20_verified:audit.canonical.verified>=20?'REQUIRES_RUNTIME_PROOF':'PENDING_CANONICAL_EVIDENCE_NOT_TRANSLATION_APPROVAL',production_baseline_accepted:false,audit,preflight,memory_unchanged:true,source_unchanged:true,memory_sha256:before,inference_requests:0,ollama_http_requests:0};
const resolution={...srdInventory,...historical,srd_es_field_hits:srd,cache_hits:preflight.cache_candidates,glossary_hits:preflight.glossary_only_hits,strings_resolved_without_ai:resolved,strings_requiring_ai:preflight.strings_requiring_ai,estimated_model_requests:preflight.estimated_model_calls,ai_avoidance_rate:resolved/Math.max(1,preflight.strings_unique),historical_unverified_is_reuse:false};
// Field-hit count is distinct from the SRD segment inventory above.
resolution.srd_es_field_hits=srd;
const sections={BABELE:{babele_entries_loaded:historical.babele_entries_loaded,babele_embedded_entries_loaded:historical.babele_embedded_entries_loaded,babele_unique_groups:audit.historical.babele_unique_groups,babele_approved_entries:audit.historical.babele_approved_entries,babele_safe_exact_hits:preflight.babele_safe_exact_hits,babele_context_required:audit.historical.babele_context_required,babele_conflicts:audit.historical.babele_conflicts},TM:{tm_entries_loaded:audit.translation_memory.entries_loaded,tm_approved_entries:audit.translation_memory.approved_entries,tm_exact_candidates:audit.translation_memory.exact_candidates,tm_exact_hits:preflight.exact_tm_candidates,tm_context_rejected:audit.translation_memory.context_rejected,tm_source_binding_unverified:audit.translation_memory.source_binding_unverified},SRD:{...auditSrdIdentities(store),srd_es_hits:srd},CACHE:{cache_current_hits:preflight.cache_candidates,legacy_cache_unverified:audit.cache.legacy_cache_unverified},TOTAL:{strings_unique:preflight.strings_unique,strings_resolved_without_ai:resolved,strings_requiring_ai:preflight.strings_requiring_ai,estimated_model_requests:preflight.estimated_model_calls,ai_avoidance_rate:resolved/Math.max(1,preflight.strings_unique)}};
// Exercise only known historical hits. Any provider invocation is an audit failure, never inference.
const originalFetch=globalThis.fetch;let forbidden=0;
globalThis.fetch=async()=>{forbidden++;throw new Error('PREFLIGHT_PROVIDER_INVOCATION_FORBIDDEN');};
const samples:any[]=[];try{for(const unit of data.units){if(samples.length>=20)break;const entry=store.exact(unit.source,'ru',unit.context);if(!entry?.historical)continue;const runtime=new TranslationRuntime(store,settings),[wire]=await runtime.translate({texts:[P.protect(unit.source).protectedText],sourceLanguage:'ru',units:[{sourceText:unit.source,context:unit.context}],file:unit.file});const restored=P.restore(wire,P.protect(unit.source).tokens);if(!restored.isValid||runtime.metrics.values.ollama_requests!==0||!runtime.units[0].origins.includes('HISTORICAL_BABELE'))throw new Error('HISTORICAL_SAMPLE_FAILED');samples.push({ru_input:unit.source,lookup:'EXACT_TM',translation_approval:entry.historical.translation_approval,canonical_identity:'UNKNOWN',source_corpus:entry.historical.source_corpus,source_file:entry.historical.source_file,field_path:unit.context.json_path,spanish_result:restored.restoredText,ollama_skipped:true});}}finally{globalThis.fetch=originalFetch;}
if(forbidden||before!==pdfHash(await fs.readFile(database)))throw new Error('READ_ONLY_AUDIT_FAILED');
await fs.writeFile('reports/canonical-memory/hit-examples.json',JSON.stringify({historical:samples,srd:{status:sections.SRD.ru_to_srd_verified_links?'REQUIRES_REAL_SAMPLE':'UNAVAILABLE_NO_VERIFIED_CANONICAL_BINDING',fabricated_samples:0},provider_invocations:forbidden},null,2));
await fs.writeFile('reports/canonical-memory/dry-run.json',JSON.stringify({...report,resolution,...sections},null,2));console.log(JSON.stringify({...report,...sections,audit:undefined,preflight:undefined}));
