import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {benchmarkGate} from '../desktop/benchmark/policy';import {inventory} from '../desktop/translation/inventory';import {PdfReuse} from '../desktop/memory/pdfReuse';
import {MemoryStore} from '../desktop/memory/store';import {pdfHash} from '../desktop/memory/pdfCorpus';import {TranslationRuntime} from '../desktop/translation/runtime';import {ThermalGuard,readNvidia,thermalState} from '../desktop/thermal';import {modelPlacement,translationPreflight} from '../desktop/translation/preflight';import {ProtectedContentEngine as P} from '../src/services/protected-content/protectedContentEngine';import {reusable} from '../desktop/translation/reuse';import {promptVersion,promptLimits} from '../desktop/translation/prompt';
const live=process.argv.includes('--run'),root=process.argv.find(a=>a.startsWith('--root='))?.slice(7)||'C:/Users/leond/AppData/Local/FoundryVTT/Data/modules/fifthpendium',directory=path.resolve(process.env.APPDATA||'','foundry-translator/translation-memory'),before=pdfHash(await fs.readFile(path.join(directory,'store.json'))),corpusBytes=await fs.readFile('tests/golden/foundry_v14_368/benchmark/corpus.json'),corpus=JSON.parse(corpusBytes.toString()),store=await new MemoryStore(directory).load();
let endpoint='http://127.0.0.1:11500';try{endpoint=JSON.parse(await fs.readFile(path.join(directory,'../provider.json'),'utf8')).endpoint;}catch{}
const url=new URL(endpoint);if(!['localhost','127.0.0.1','[::1]'].includes(url.hostname)||url.username||url.password||url.search||url.hash||url.pathname!=='/')throw new Error('LOCAL_ENDPOINT_REQUIRED');
let installed:string[]=[];try{const response=await fetch(endpoint+'/api/tags',{signal:AbortSignal.timeout(3000)});if(response.ok)installed=((await response.json()) as any).models.map((m:any)=>m.name);}catch{}
const gpu=await readNvidia(),report:any={schema_version:1,corpus_hash:pdfHash(corpusBytes),prompt:{version:promptVersion,limits:promptLimits},baseline_memory_sha256:before,mode:live?'REQUESTED_REAL_BENCHMARK':'METADATA_ONLY_NO_INFERENCE',gpu,semantic_quality:'REQUIRES_HUMAN_BLIND_REVIEW',rows:[]};
// The historic six-case runner must not be mistaken for the real T043 comparison.
if(live)throw new Error('T043_REAL_CORPUS_REQUIRED: use benchmark:plan; real comparison awaits missing models and the frozen corpus runner.');
let gate='NOT_REQUESTED';let nativeUnits:Awaited<ReturnType<typeof inventory>>['units']=[];report.gate=gate;
for(const model of ['translategemma:4b','translategemma:12b','translategemma:27b'])for(const mode of ['QUALITY_PURE','PIPELINE_REAL'])for(const language of ['en','ru'] as const){
 const row:any={model,mode,language,corpus_hash:report.corpus_hash,status:!installed.includes(model)?'NOT_INSTALLED':!live?'NOT_RUN':gate!=='PASS'?gate:'RUNNING'};report.rows.push(row);if(row.status!=='RUNNING')continue;
 const temporary=await fs.mkdtemp(path.join(os.tmpdir(),'gemma-bench-')),guard=new ThermalGuard(),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(new Error('BENCHMARK_TIMEOUT')),600000);
 try{
  if(mode==='PIPELINE_REAL'){await fs.copyFile(path.join(directory,'store.json'),path.join(temporary,'store.json'));await fs.cp(path.join(directory,'pdf-reference'),path.join(temporary,'pdf-reference'),{recursive:true});}
  const memory=await new MemoryStore(temporary).load(),runtime=new TranslationRuntime(memory,{endpoint,model});runtime.thermal=guard;await guard.start();const started=performance.now();row.cases=[];
  const reuse=new PdfReuse(store),samples=nativeUnits.filter(u=>u.source.length<=1200&&(/[\u0400-\u04ff]/.test(u.source)?'ru':'en')===language).sort((a,b)=>Number(!!(store.canonical(b.context)||reuse.canonical(b.source,b.context)))-Number(!!(store.canonical(a.context)||reuse.canonical(a.source,a.context)))||a.file.localeCompare(b.file)||JSON.stringify(a.context.json_path).localeCompare(JSON.stringify(b.context.json_path))).slice(0,6);
  const cases=mode==='QUALITY_PURE'?corpus.cases.map((item:any)=>({id:item.id,source:item[language],reference:item.reference,context:{system:'dnd5e',document_type:'weapon',field_type:item.field}})):samples.map(item=>({id:item.file+':'+JSON.stringify(item.context.json_path),source:item.source,reference:null,context:item.context}));row.sample_hash=pdfHash(JSON.stringify(cases));
  for(const item of cases){const source=item.source,protectedSource=P.protect(source);try{const [wire]=await runtime.translate({texts:[protectedSource.protectedText],sourceLanguage:language,units:[{sourceText:source,context:item.context}]},controller.signal),target=P.restore(wire,protectedSource.tokens).restoredText;row.cases.push({id:item.id,target,reference:item.reference,integrity:reusable(source,target,item.context),matches_reference:item.reference===null?null:target===item.reference});}catch(error){controller.signal.throwIfAborted();row.cases.push({id:item.id,status:'FAILED',reason:error instanceof Error?error.message:'UNKNOWN'});}}
  row.metrics=runtime.metrics.finish();row.prompt=runtime.promptAudit();row.total_time=(performance.now()-started)/1000;row.strings_per_second=cases.length/row.total_time;row.tokens_per_second=row.metrics.eval_duration?row.metrics.generated_tokens/(row.metrics.eval_duration/1e9):null;row.placement=await modelPlacement({endpoint,model});row.thermal=guard.report();row.status='AWAITING_SEMANTIC_REVIEW';
 }catch(error){row.status='ABORTED';row.reason=error instanceof Error?error.message:'UNKNOWN';row.thermal=guard.report();}
 finally{guard.stop();clearTimeout(timeout);const resolved=path.resolve(temporary);if(!resolved.startsWith(path.resolve(os.tmpdir())+path.sep)||!path.basename(resolved).startsWith('gemma-bench-'))throw new Error('TEMP_PATH_INVALID');await fs.rm(resolved,{recursive:true,force:true});}
}
if(before!==pdfHash(await fs.readFile(path.join(directory,'store.json'))))throw new Error('BENCHMARK_CHANGED_MEMORY');report.memory_unchanged=true;await fs.mkdir('reports/benchmark',{recursive:true});await fs.writeFile('reports/benchmark/matrix.json',JSON.stringify(report,null,2));console.log(JSON.stringify({gate,installed,rows:report.rows.map(({model,mode,language,status}:any)=>({model,mode,language,status})),memory_unchanged:true}));
