import fs from 'node:fs/promises';
import path from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createHash} from 'node:crypto';
import {MemoryStore} from '../desktop/memory/store';
import {importSpanish} from '../desktop/memory/spanishImport';

const [moduleRoot,spanish]=process.argv.slice(2);
if(!moduleRoot||!spanish)throw new Error('Usage: importSpanishCandidates.ts moduleRoot spanishFolder');
const processes=await promisify(execFile)('powershell.exe',['-NoProfile','-NonInteractive','-Command',"@(Get-CimInstance Win32_Process | Where-Object { $_.Name -eq 'Traductor Foundry.exe' -or ($_.Name -eq 'electron.exe' -and $_.CommandLine -like '*Translate*') }).Count"],{windowsHide:true});
if(Number(processes.stdout.trim())!==0)throw new Error('Close the translator before importing its private database.');
const directory=path.resolve(process.env.APPDATA||'','foundry-translator','translation-memory');
const database=path.join(directory,'store.json');
const bytes=await fs.readFile(database);
const timestamp=new Date().toISOString().replace(/[:.]/g,'-');
const backup=path.join(directory,'backups',timestamp+'-before-spanish.json');
await fs.mkdir(path.dirname(backup),{recursive:true});
await fs.writeFile(backup,bytes,{flag:'wx'});
const store=await new MemoryStore(directory).load();
const before=store.statistics();
const originalIds=new Set(store.readEntries().map(entry=>entry.id));
const imported=await importSpanish(spanish,moduleRoot,store);
const after=store.statistics();
if(after.approved_entries!==before.approved_entries||[...originalIds].some(id=>!store.readEntries().some(entry=>entry.id===id)))throw new Error('IMPORT_POSTCONDITION_FAILED');
const report={schema_version:1,mode:'IMPORT_CANDIDATES_ONLY',before,after,imported,backup,original_entries_preserved:true,sha256_before:createHash('sha256').update(bytes).digest('hex'),sha256_after:createHash('sha256').update(await fs.readFile(database)).digest('hex')};
await fs.mkdir('reports/thermal-memory',{recursive:true});
await fs.writeFile('reports/thermal-memory/spanish-import.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report));
