import {it,expect,afterEach,vi} from 'vitest';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {MemoryStore} from '../../desktop/memory/store';import {TranslationRuntime} from '../../desktop/translation/runtime';import {providers} from '../../desktop/providers';import {fieldIdentity,evidenceMatches} from '../../desktop/memory/canonicalEvidence';import {ProtectedContentEngine as P} from '../../src/services/protected-content/protectedContentEngine';import {jsonQualityGate} from '../../src/services/validation/qualityGate';import {auditReuse} from '../../desktop/memory/reuseAudit';
const roots:string[]=[];afterEach(async()=>{vi.restoreAllMocks();for(const root of roots.splice(0))await fs.rm(root,{recursive:true,force:true});});
const types=['Actor','Item','JournalEntry','RollTable','Scene'] as const;
const cases=types.flatMap((type,t)=>Array.from({length:4},(_,n)=>({id:`${type}-${n}`,type,documentId:String(t*4+n).padStart(16,'0'),field:n%2?'description':'name',en:n%2?'The old tower stands near the forest.':'Vampire',ru:n%2?'Старая башня стоит рядом с лесом.':'Вампир',es:n%2?'La antigua torre se alza junto al bosque.':'Vampiro'})));
/** Approved synthetic witnesses exercise the bridge; never count as production coverage. */
it.each(cases)('verified synthetic field bridge $id resolves RU without any provider',async item=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'canonical-golden-'));roots.push(root);const store=await new MemoryStore(root).load(),context={system:'dnd5e',module:'test',document_type:item.type,field_type:item.field,canonical_uuid:`Compendium.test.${item.type.toLowerCase()}.${item.type}.${item.documentId}`,canonical_version:'1',json_path:[item.field]};
 const id=await store.candidate(item.en,item.es,'en',context,'manual-reviewed-fixture','');expect(store.canonical(context)).toBeUndefined();await store.approve(id);
 const reloaded=await new MemoryStore(root).load(),entry=reloaded.readEntries()[0];expect(entry.canonical_evidence?.decision).toBe('VERIFIED');expect(entry.canonical_evidence?.match_type).toBe('APPROVED_MANUAL');expect(entry.canonical_evidence?.approved_by).toBe('LOCAL_USER');expect(fieldIdentity(entry)?.field_path).toEqual([item.field]);expect(evidenceMatches(entry)).toBe(true);
 const spy=vi.spyOn(providers.ollama,'translate'),runtime=new TranslationRuntime(reloaded,{endpoint:'http://127.0.0.1:11500',model:'translategemma:27b'});const [wire]=await runtime.translate({texts:[P.protect(item.ru).protectedText],sourceLanguage:'ru',units:[{sourceText:item.ru,context}]});const translated=P.restore(wire,P.protect(item.ru).tokens).restoredText;expect(translated).toBe(item.es);expect(spy).not.toHaveBeenCalled();expect(runtime.metrics.values.canonical_hits).toBe(1);
 const before={_id:item.documentId,[item.field]:item.ru,values:[1,2],icon:'icons/example.webp'},after={...before,[item.field]:translated};expect(jsonQualityGate(JSON.stringify(before),JSON.stringify(after),[[item.field]]).status).toBe('PASS');const audit=await auditReuse(reloaded,[{file:'fixture.json',source:item.ru,context}],{endpoint:'http://127.0.0.1:11500',model:'translategemma:27b'});expect(audit.canonical.usable).toBe(1);expect(audit.canonical.demonstrable_ru_documents).toBe(1);
 expect(reloaded.canonical({...context,json_path:['other']})).toBeUndefined();expect(reloaded.canonical({...context,canonical_version:'2'})).toBeUndefined();expect(reloaded.canonical({...context,canonical_uuid:context.canonical_uuid.replace('.test.','.other.')})).toBeUndefined();
});
