import {it,expect,afterEach,vi} from 'vitest';
import fs from 'node:fs/promises';import path from 'node:path';
import {pdfFixture} from './pdfFixtures';import {auditHistoricalBabele} from '../../desktop/memory/historicalBabeleImport';import {MemoryStore} from '../../desktop/memory/store';import {auditReuse} from '../../desktop/memory/reuseAudit';
import {importSpanish} from '../../desktop/memory/spanishImport';
const roots:string[]=[];afterEach(async()=>{vi.restoreAllMocks();for(const r of roots.splice(0))await fs.rm(r,{recursive:true,force:true});});
async function fixture(entry:any={name:'Espada larga'},mapping:any={}){const f=await pdfFixture();roots.push(f.root);const folder=path.join(f.root,'historical');await fs.mkdir(folder);const file=path.join(folder,'test.items.json');await fs.writeFile(file,JSON.stringify({mapping,entries:{abcdefghijklmnop:entry}}));const context={system:'dnd5e',module:'test',document_type:'weapon',field_type:'name',canonical_uuid:'Compendium.test.items.Item.abcdefghijklmnop',canonical_version:'1',json_path:['name']};const unit={file:'sword.json',source:'Длинный меч',context};return {...f,folder,file,unit};}
it('detects exact historical candidates without approval, canonical promotion or network',async()=>{const f=await fixture();await f.store.cache('legacy','x');const before=await fs.readFile(path.join(f.memory,'store.json'));const source=await fs.readFile(f.file);const network=vi.spyOn(globalThis,'fetch').mockRejectedValue(new Error('FORBIDDEN'));const r=await auditHistoricalBabele(f.folder,[f.unit],f.store);expect(r.babele_field_candidates).toBe(1);expect(r.babele_ru_es_exact_candidates).toBe(0);expect(r.babele_historical_unverified_hits).toBe(1);expect(r.babele_approved_hits).toBe(0);expect(r.canonical_mappings_created).toBe(0);expect(network).not.toHaveBeenCalled();expect(await fs.readFile(f.file)).toEqual(source);expect(await fs.readFile(path.join(f.memory,'store.json'))).toEqual(before);});
it('reuses explicitly reviewed exact-only history but cannot bridge a changed RU source',async()=>{const f=await fixture();const [id]=await f.store.candidateBatch([{source:f.unit.source,target:'Espada larga',language:'ru',context:f.unit.context,engine:'historical-babele',model:'',reuseScope:'EXACT_SOURCE_ONLY'}]);await f.store.approve(id);const r=await auditHistoricalBabele(f.folder,[f.unit],f.store);expect(r.babele_approved_hits).toBe(1);expect(f.store.exact(f.unit.source,'ru',f.unit.context)?.translated_text).toBe('Espada larga');expect(f.store.exact('Другой меч','ru',f.unit.context)).toBeUndefined();expect(f.store.canonical(f.unit.context)).toBeUndefined();const audit=await auditReuse(f.store,[f.unit],{model:'translategemma:27b',endpoint:'http://127.0.0.1:11500'});expect(audit.canonical.mappings_loaded).toBe(0);});
it('keeps exact-only scope through edit, review and persistence',async()=>{const f=await fixture();const [id]=await f.store.candidateBatch([{source:f.unit.source,target:'Espada larga',language:'ru',context:f.unit.context,engine:'historical-babele',model:'',reuseScope:'EXACT_SOURCE_ONLY'}]);const edited=await f.store.review({id,action:'EDIT',translatedText:'Espadón'});await f.store.approve(edited.id);const reload=await new MemoryStore(f.memory).load();expect(reload.canonical(f.unit.context)).toBeUndefined();expect(reload.exact(f.unit.source,'ru',f.unit.context)?.translated_text).toBe('Espadón');});
it('does not execute converters or infer missing field mappings',async()=>{const f=await fixture({description:'Descripción',activities:'Actividad'},{activities:{path:'name',converter:'evil'}});const r=await auditHistoricalBabele(f.folder,[f.unit],f.store);expect(r.reasons.HISTORICAL_FIELD_MAPPING_NOT_EXPLICIT).toBe(1);expect(r.reasons.HISTORICAL_CONVERTER_NOT_EXECUTED).toBe(1);expect(r.babele_ru_es_exact_candidates).toBe(0);});
it('recognizes a literal RU name key as exact textual evidence without treating it as approval',async()=>{const f=await fixture();await fs.writeFile(f.file,JSON.stringify({entries:{[f.unit.source]:{name:'Espada larga'}}}));const r=await auditHistoricalBabele(f.folder,[f.unit],f.store);expect(r.babele_ru_es_exact_candidates).toBe(1);expect(r.babele_approved_hits).toBe(0);expect(r.babele_historical_unverified_hits).toBe(1);expect(r.reasons.HISTORICAL_ORIGINAL_FIELD_TEXT_UNAVAILABLE).toBeUndefined();});
it('rejects changed references and duplicate document ambiguity',async()=>{const f=await fixture({name:'Espada @UUID[Item.changed]'});const r=await auditHistoricalBabele(f.folder,[{...f.unit,source:'Меч @UUID[Item.original]'}],f.store);expect(r.reasons.HISTORICAL_FIELD_VALIDATION_FAILED).toBe(1);const duplicate=await auditHistoricalBabele(f.folder,[f.unit,{...f.unit,file:'other.json'}],f.store);expect(duplicate.reasons.HISTORICAL_SOURCE_NOT_UNIQUE).toBe(1);});
it('imports a literal RU name into internal candidate TM without inferring descriptions or canonical approval',async()=>{const f=await fixture();await fs.writeFile(path.join(f.moduleRoot,'packs/items/_source/sword.json'),JSON.stringify({_id:'abcdefghijklmnop',name:f.unit.source,type:'weapon',_stats:{systemId:'dnd5e'}}));await fs.writeFile(f.file,JSON.stringify({mapping:{description:'system.description.value'},entries:{[f.unit.source]:{name:'Espada larga',description:'Sin fuente rusa demostrada'}}}));const r=await importSpanish(f.folder,f.moduleRoot,f.store);expect(r.candidates).toBe(1);expect(r.approved_automatically).toBe(0);const entry=f.store.readEntries()[0];expect(entry.reuse_scope).toBe('EXACT_SOURCE_ONLY');expect(entry.approved).toBe(false);await f.store.approve(entry.id);expect(f.store.exact(f.unit.source,'ru',entry)?.translated_text).toBe('Espada larga');expect(f.store.canonical(entry)).toBeUndefined();});
