import { afterEach,expect,it,vi } from 'vitest';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import { MemoryStore } from '../../desktop/memory/store';import { providers } from '../../desktop/providers';import { runLoggedBatch } from '../../desktop/logging/runReport';import { IncrementalSession } from '../../desktop/memory/incremental';
import { JsonEngine } from '../../src/services/json/jsonEngine';
const roots:string[]=[];const settings={endpoint:'http://localhost:11434',model:'translategemma:27b'};
afterEach(async()=>{vi.restoreAllMocks();for(const root of roots.splice(0))await fs.rm(root,{recursive:true,force:true});});
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'incremental-'));roots.push(root);const input=path.join(root,'input'),sources=path.join(input,'packs/items/_source');await fs.mkdir(sources,{recursive:true});const store=await new MemoryStore(path.join(root,'memory')).load();const spy=vi.spyOn(providers.ollama,'translate').mockImplementation(async(_settings,request)=>request.texts.map(source=>({Sword:'Espada',Axe:'Hacha',Armor:'Armadura',Bow:'Arco',Staff:'Bastón'}[source]||source)));let ordinal=0;
 const run=async(signal=new AbortController().signal)=>{let directory='';const progress=await runLoggedBatch(input,path.join(root,'output-'+ordinal++),settings,store,path.join(root,'logs'),signal,()=>{},'en','run',[],value=>directory=value);return {progress,summary:JSON.parse(await fs.readFile(path.join(directory,'summary.json'),'utf8')),directory};};
 return {root,input,sources,store,spy,run};}
it('classifies unchanged/changed/new/removed and translates only new or changed content',async()=>{
 const {sources,store,spy,run}=await fixture();for(const [name,source] of [['a','Sword'],['b','Axe'],['c','Armor']])await fs.writeFile(path.join(sources,name+'.json'),JSON.stringify({name:source}));const first=await run();expect(first.summary.incremental).toMatchObject({new:3,changed:0,unchanged:0,removed:0,baseline_committed:true});spy.mockClear();vi.spyOn(store,'getCache').mockReturnValue(undefined);
 await fs.writeFile(path.join(sources,'b.json'),'{"name":"Bow"}');await fs.rm(path.join(sources,'c.json'));await fs.writeFile(path.join(sources,'d.json'),'{"name":"Staff"}');const second=await run();expect(second.summary.incremental).toMatchObject({unchanged:1,changed:1,new:1,removed:1,baseline_committed:true});expect(spy).toHaveBeenCalledTimes(2);expect(second.summary.translation_provenance.some((unit:any)=>unit.incremental&&unit.origins.includes('CACHE'))).toBe(true);
});
it('an identical module produces zero provider requests even without ordinary cache',async()=>{
 const {sources,store,spy,run}=await fixture();await fs.writeFile(path.join(sources,'a.json'),'{"name":"Sword"}');await run();spy.mockClear();vi.spyOn(store,'getCache').mockReturnValue(undefined);const result=await run();expect(result.summary.incremental.unchanged).toBe(1);expect(spy).not.toHaveBeenCalled();
});
it('a manual rejection invalidates baseline reuse and recovers the original',async()=>{
 const {sources,store,spy,run}=await fixture();await fs.writeFile(path.join(sources,'a.json'),'{"name":"Sword"}');await run();await store.review({id:store.entries()[0].id,action:'REJECT'});spy.mockClear();const result=await run();expect(spy).toHaveBeenCalledTimes(1);expect(result.summary.incremental.baseline_committed).toBe(false);expect(result.summary.translation_provenance[0].origins).toContain('ORIGINAL_FALLBACK');expect(result.progress.outcomes?.[0].status).toBe('WARNING');
});
it('cancelled updates preserve the previous baseline and do not invent removals',async()=>{
 const {root,sources,spy,run}=await fixture();await fs.writeFile(path.join(sources,'a.json'),'{"name":"Sword"}');await run();const directory=path.join(root,'memory/incremental'),file=path.join(directory,(await fs.readdir(directory))[0]);const original=await fs.readFile(file);await fs.writeFile(path.join(sources,'a.json'),'{"name":"Bow"}');const controller=new AbortController();spy.mockImplementation(async()=>{controller.abort();return ['Arco'];});const result=await run(controller.signal);expect(result.summary.status).toBe('CANCELLED');expect(result.summary.incremental).toMatchObject({complete:false,baseline_committed:false,removed:0});expect(await fs.readFile(file)).toEqual(original);
});
it('rejects a corrupt baseline before creating an output',async()=>{
 const {root,sources,run}=await fixture();await fs.writeFile(path.join(sources,'a.json'),'{"name":"Sword"}');await run();const directory=path.join(root,'memory/incremental'),file=path.join(directory,(await fs.readdir(directory))[0]);await fs.writeFile(file,'{"schema_version":1,"units":[{}]}');await expect(run()).rejects.toThrow('INCREMENTAL_SCHEMA_INVALID');await expect(fs.stat(path.join(root,'output-1'))).rejects.toThrow();
});
it('revalidates tampered targets rather than blindly trusting an unchanged hash',async()=>{
 const {root,sources,store,spy,run}=await fixture();await fs.writeFile(path.join(sources,'a.json'),'{"name":"Sword"}');await run();const directory=path.join(root,'memory/incremental'),file=path.join(directory,(await fs.readdir(directory))[0]);const value=JSON.parse(await fs.readFile(file,'utf8'));value.units[0].target='Translation: Espada';await fs.writeFile(file,JSON.stringify(value));spy.mockClear();vi.spyOn(store,'getCache').mockReturnValue(undefined);const result=await run();expect(spy).toHaveBeenCalledTimes(1);expect(result.summary.translation_provenance[0].origins).toEqual(['TRANSLATEGEMMA']);
});
it('reports baseline disk failures and keeps previously validated source and baseline intact',async()=>{
 const {root,sources,run}=await fixture();await fs.writeFile(path.join(sources,'a.json'),'{"name":"Sword"}');await run();const directory=path.join(root,'memory/incremental'),file=path.join(directory,(await fs.readdir(directory))[0]);const original=await fs.readFile(file);await fs.writeFile(path.join(sources,'a.json'),'{"name":"Bow"}');const rename=fs.rename;vi.spyOn(fs,'rename').mockImplementation(async(from,to)=>{if(String(to).includes(path.join('memory','incremental')))throw Object.assign(new Error('full'),{code:'ENOSPC'});return rename(from,to);});await expect(run()).rejects.toThrow('full');expect(await fs.readFile(file)).toEqual(original);expect(await fs.readFile(path.join(sources,'a.json'),'utf8')).toBe('{"name":"Bow"}');
 const reports=await fs.readdir(path.join(root,'logs/runs'));const summaries=await Promise.all(reports.map(async name=>JSON.parse(await fs.readFile(path.join(root,'logs/runs',name,'summary.json'),'utf8'))));expect(summaries.some(summary=>summary.status==='ERROR'&&summary.incremental.baseline_committed===false)).toBe(true);
});
it('refuses to commit pending or recovered units',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'baseline-'));roots.push(root);const session=await new IncrementalSession(root,'test').load();await expect(session.commit([{publication:'RECOVERED',quality:'FAILED'}] as any,new AbortController().signal)).rejects.toThrow('INCREMENTAL_UNVALIDATED');
});
it('attributes a whole-file fallback to the restored original rather than the unpublished producer',async()=>{
 const {sources,run}=await fixture();await fs.writeFile(path.join(sources,'a.json'),'{"name":"Sword"}');
 vi.spyOn(JsonEngine,'reconstruct').mockImplementation(()=>{throw new Error('FILE_VALIDATION_FAILED');});
 const result=await run();expect(result.summary.translation_provenance[0]).toMatchObject({publication:'RECOVERED',provider:null,model:null,reason:'FILE_ORIGINAL_RESTORED'});
 expect(result.summary.translation_provenance[0].source_hash).toBe(result.summary.translation_provenance[0].target_hash);
 expect(result.summary.incremental.baseline_committed).toBe(false);
});
it('keeps repeated native registrations distinct without inventing a JSON path',async()=>{
 const {root,input,store,run}=await fixture();await fs.mkdir(path.join(input,'lang'));await fs.writeFile(path.join(input,'lang/en.json'),'{"name":"Sword"}');await fs.writeFile(path.join(input,'module.json'),JSON.stringify({id:'test',languages:[{lang:'en',name:'English',path:'lang/en.json'},{lang:'en',name:'English extra',path:'lang/en.json'}]}));const result=await run();expect(result.summary.incremental).toMatchObject({new:2,baseline_committed:true});expect(result.summary.translation_provenance.map((unit:any)=>unit.json_path)).toEqual([['name'],['name']]);expect(new Set(result.summary.translation_provenance.map((unit:any)=>unit.locator_id)).size).toBe(2);expect(result.progress.generatedLocalizations).toHaveLength(2);expect(store.entries().length).toBe(1);
});
it('publishes a review-only consistency warning without rewriting contextual alternatives',async()=>{
 const {root,sources,spy,run}=await fixture();await fs.writeFile(path.join(sources,'a.json'),'{"name":"Saving Throw","description":"Meaning A"}');await fs.writeFile(path.join(sources,'b.json'),'{"name":"Saving Throw","description":"Meaning B"}');spy.mockImplementation(async(_settings,request)=>request.texts.map(text=>text==='Saving Throw'?(request.context?.notes?.includes('Meaning A')?'Tirada de Salvación':'Salvación'):text.replace('Meaning','Significado')));const result=await run();expect(result.summary.terminology_consistency.warning_count).toBe(1);const a=JSON.parse(await fs.readFile(path.join(root,'output-0/packs/items/_source/a.json'),'utf8')),b=JSON.parse(await fs.readFile(path.join(root,'output-0/packs/items/_source/b.json'),'utf8'));expect(a.name).toBe('Tirada de Salvación');expect(b.name).toBe('Salvación');expect(JSON.parse(await fs.readFile(path.join(result.directory,'warnings.json'),'utf8')).some((item:any)=>item.reason==='TERMINOLOGY_VARIANTS')).toBe(true);
});
it('never reuses a LibreTranslate fallback as though it came from the preferred Ollama model',async()=>{
 const {root,input,sources,store,spy}=await fixture();await fs.writeFile(path.join(sources,'a.json'),'{"name":"Sword"}');const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(Response.json({translatedText:'Espada'}));spy.mockRejectedValue(new Error('offline'));const fallback={...settings,fallback:true};
 await runLoggedBatch(input,path.join(root,'fallback-1'),fallback,store,path.join(root,'logs'),new AbortController().signal,()=>{},'en','first');spy.mockResolvedValue(['Espada']);spy.mockClear();
 await runLoggedBatch(input,path.join(root,'fallback-2'),fallback,store,path.join(root,'logs'),new AbortController().signal,()=>{},'en','second');expect(spy).toHaveBeenCalledOnce();expect(fetcher).toHaveBeenCalledOnce();
});
it('reuses a module update in a different folder when its native module ID is unchanged',async()=>{
 const {root,input,sources,store,spy,run}=await fixture();await fs.writeFile(path.join(input,'module.json'),'{"id":"stable-module","version":"1"}');await fs.writeFile(path.join(sources,'a.json'),'{"name":"Sword"}');await run();const update=path.join(root,'download-v2');await fs.mkdir(path.join(update,'packs/items/_source'),{recursive:true});await fs.writeFile(path.join(update,'module.json'),'{"id":"stable-module","version":"2"}');await fs.writeFile(path.join(update,'packs/items/_source/a.json'),'{"name":"Sword"}');spy.mockClear();vi.spyOn(store,'getCache').mockReturnValue(undefined);let report='';await runLoggedBatch(update,path.join(root,'updated-output'),settings,store,path.join(root,'logs'),new AbortController().signal,()=>{},'en','update',[],directory=>report=directory);expect(spy).not.toHaveBeenCalled();const summary=JSON.parse(await fs.readFile(path.join(report,'summary.json'),'utf8'));expect(summary.incremental.unchanged).toBe(1);expect(summary.translation_provenance[0].module).toBe('stable-module');
});
