import {it,expect,afterEach,vi} from 'vitest';import fs from 'node:fs/promises';import path from 'node:path';
import {pdfFixture} from './pdfFixtures';import {resolvePdfMemory,approveVerifiedPdf} from '../../desktop/memory/pdfResolution';import {canonicalResolution,applyCanonicalResolution} from '../../desktop/memory/canonicalResolution';import {inventory} from '../../desktop/translation/inventory';import {createPdfAlignment} from '../../desktop/memory/pdfAlignment';import {listMemory} from '../../desktop/memory/review';import {PdfReuse} from '../../desktop/memory/pdfReuse';
const roots:string[]=[];afterEach(async()=>{vi.restoreAllMocks();for(const root of roots.splice(0))await fs.rm(root,{recursive:true,force:true});});async function fixture(){const f=await pdfFixture();roots.push(f.root);return f;}
it('creates a proven RU binding without approving the imported JSON and remains idempotent',async()=>{const {store,pair,moduleRoot}=await fixture();await fs.writeFile(path.join(moduleRoot,'packs/items/_source/sword.json'),JSON.stringify({_id:'abcdefghijklmnop',type:'weapon',name:'Длинный меч',_stats:{systemId:'dnd5e'}}));const data=await inventory(moduleRoot),u=data.units[0],manual=await store.candidate(u.source,'Espada larga','ru',u.context,'manual-spanish-import','');await store.approve(await pair());const plan=canonicalResolution(store,data.units);expect((await applyCanonicalResolution(store,moduleRoot,plan.input_hash)).approved).toBe(1);expect(store.readEntries().find(e=>e.id===manual)?.approved).toBe(false);expect(new PdfReuse(store).canonical(u.source,u.context)?.translated_text).toBe('Espada larga');expect((await applyCanonicalResolution(store,moduleRoot,canonicalResolution(store,data.units).input_hash)).approved).toBe(0);});
it('is deterministic and never verifies page/score/name evidence alone',async()=>{const {store,pair}=await fixture();await pair();const a=resolvePdfMemory(store);expect(a).toEqual(resolvePdfMemory(store));expect(a.counts.AMBIGUOUS).toBe(1);expect(a.auto_approvable).toEqual([]);expect((await approveVerifiedPdf(store,a.input_hash)).approved).toBe(0);expect(store.statistics().approved_entries).toBe(0);});
it('classifies explicit selection as high confidence, without automatic approval',async()=>{const {store}=await fixture();const rows=[...store.pdfCorpus.segments.values()],a=rows.find(e=>e.text==='Longsword')!,b=rows.find(e=>e.text==='Espada larga')!;await createPdfAlignment(store,a.id,b.id);expect(resolvePdfMemory(store).counts.HIGH_CONFIDENCE).toBe(1);expect(store.statistics().approved_entries).toBe(0);});
it('propagates an approved identical pair atomically, deduplicates by translation and filters review by confidence',async()=>{const {store,pair}=await fixture();const a=await pair();const original=store.readEntries()[0];const b=await createPdfAlignment(store,original.pdf!.source.segment,original.pdf!.target.segment);await store.approve(a);const plan=resolvePdfMemory(store);expect(plan.auto_approvable).toEqual([b.id]);expect(plan.groups_total).toBe(1);expect(plan.duplicates).toBe(1);expect(listMemory(store,{source:'PDF',resolution:'VERIFIED'}).total).toBe(2);await approveVerifiedPdf(store,plan.input_hash);expect(store.statistics().approved_entries).toBe(2);await expect(approveVerifiedPdf(store,plan.input_hash)).rejects.toThrow('PDF_RESOLUTION_STALE');});
it('blocks conflicting approved alternatives and invalid evidence instead of picking the highest score',async()=>{const {store,pair}=await fixture();await store.approve(await pair(1,1));await store.approve(await pair(1,4));expect(resolvePdfMemory(store).counts.AMBIGUOUS).toBe(2);const first=store.readEntries()[0];await store.review({id:first.id,action:'REJECT'});expect(resolvePdfMemory(store).counts.REJECTED).toBe(1);expect(()=>listMemory(store,{source:'PDF',resolution:'GUESS' as any})).toThrow('MEMORY_QUERY_INVALID');});
it('rolls back all propagated approvals on ENOSPC',async()=>{const {store,pair}=await fixture();const a=await pair(),e=store.readEntries()[0];await createPdfAlignment(store,e.pdf!.source.segment,e.pdf!.target.segment);await store.approve(a);const plan=resolvePdfMemory(store);const rename=vi.spyOn(fs,'rename').mockRejectedValue(Object.assign(new Error('disk full'),{code:'ENOSPC'}));await expect(approveVerifiedPdf(store,plan.input_hash)).rejects.toThrow('disk full');expect(store.statistics().approved_entries).toBe(1);rename.mockRestore();});
it('joins RU only on complete native identity and approved SRD pair, rejecting version/path/conflicts',async()=>{const {store,pair,moduleRoot}=await fixture();const file='packs/items/_source/sword.json';await fs.writeFile(path.join(moduleRoot,file),JSON.stringify({_id:'abcdefghijklmnop',type:'weapon',name:'Длинный меч',_stats:{systemId:'dnd5e'}}));const data=await inventory(moduleRoot),u=data.units[0];await store.candidate(u.source,'Espada larga','ru',u.context,'manual-spanish-import','');expect(canonicalResolution(store,data.units).verified_bindings).toBe(0);await store.approve(await pair());expect(canonicalResolution(store,data.units).verified_bindings).toBe(1);expect(canonicalResolution(store,[{...u,context:{...u.context,canonical_version:'2'}}]).verified_bindings).toBe(0);expect(canonicalResolution(store,[{...u,context:{...u.context,json_path:['other']}}]).verified_bindings).toBe(0);await store.candidate(u.source,'Embestida','ru',u.context,'manual-spanish-import','');expect(canonicalResolution(store,data.units).conflicting_units).toBe(1);});
